/**
 * klantinteracties
 *  Description WIP. 
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: standaarden.ondersteuning@vng.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.atos.client.klanten.api;

import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.DELETE;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.PATCH;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.PUT;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.ProcessingException;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.QueryParam;
import net.atos.client.klanten.model.generated.ActorKlantcontact;
import net.atos.client.klanten.model.generated.PaginatedActorKlantcontactList;
import net.atos.client.klanten.model.generated.PatchedActorKlantcontact;
import org.eclipse.microprofile.rest.client.annotation.RegisterProvider;
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

import java.util.UUID;

/**
 * klantinteracties
 *
 * <p> Description WIP. 
 *
 */

@RegisterRestClient
@RegisterProvider(ApiExceptionMapper.class)
@Path("/actorklantcontacten")
public interface ActorKlantcontactenApi  {

    /**
     * Maak een actor klantcontact aan.
     *
     * Maak een actor klantcontact aan.
     *
     */
    @POST
    
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    ActorKlantcontact actorklantcontactenCreate(ActorKlantcontact actorKlantcontact) throws ApiException, ProcessingException;

    /**
     * Verwijder een aactor klantcontactctor.
     *
     * Verwijder een actor klantcontact.
     *
     */
    @DELETE
    @Path("/{uuid}")
    void actorklantcontactenDestroy(@PathParam("uuid") UUID uuid) throws ApiException, ProcessingException;

    /**
     * Alle actor klantcontacten opvragen.
     *
     * Alle actor klantcontacten opvragen.
     *
     */
    @GET
    
    @Produces({ "application/json" })
    PaginatedActorKlantcontactList actorklantcontactenList(@QueryParam("actor__url") String actorUrl, @QueryParam("actor__uuid") UUID actorUuid, @QueryParam("klantcontact__url") String klantcontactUrl, @QueryParam("klantcontact__uuid") UUID klantcontactUuid, @QueryParam("page") Integer page) throws ApiException, ProcessingException;

    /**
     * Werk een actor klantcontact deels bij.
     *
     * Werk een actor klantcontact deels bij.
     *
     */
    @PATCH
    @Path("/{uuid}")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    ActorKlantcontact actorklantcontactenPartialUpdate(@PathParam("uuid") UUID uuid, PatchedActorKlantcontact patchedActorKlantcontact) throws ApiException, ProcessingException;

    /**
     * Een specifiek actor klantcontact opvragen.
     *
     * Een specifiek actor klantcontact opvragen.
     *
     */
    @GET
    @Path("/{uuid}")
    @Produces({ "application/json" })
    ActorKlantcontact actorklantcontactenRetrieve(@PathParam("uuid") UUID uuid) throws ApiException, ProcessingException;

    /**
     * Werk een actor klantcontact in zijn geheel bij.
     *
     * Werk een actor klantcontact in zijn geheel bij.
     *
     */
    @PUT
    @Path("/{uuid}")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    ActorKlantcontact actorklantcontactenUpdate(@PathParam("uuid") UUID uuid, ActorKlantcontact actorKlantcontact) throws ApiException, ProcessingException;
}
