/**
 * klantinteracties
 *  Description WIP. 
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: standaarden.ondersteuning@vng.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.atos.client.klanten.api;

import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.DELETE;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.PATCH;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.PUT;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.ProcessingException;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.QueryParam;
import net.atos.client.klanten.model.generated.Betrokkene;
import net.atos.client.klanten.model.generated.PaginatedBetrokkeneList;
import net.atos.client.klanten.model.generated.PatchedBetrokkene;
import org.eclipse.microprofile.rest.client.annotation.RegisterProvider;
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

import java.util.UUID;

/**
 * klantinteracties
 *
 * <p> Description WIP. 
 *
 */

@RegisterRestClient
@RegisterProvider(ApiExceptionMapper.class)
@Path("/betrokkenen")
public interface BetrokkenenApi  {

    /**
     * Maak een betrokkene aan.
     *
     * Maak een betrokkene aan.
     *
     */
    @POST
    
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    Betrokkene betrokkenenCreate(Betrokkene betrokkene) throws ApiException, ProcessingException;

    /**
     * Verwijder een betrokkene.
     *
     * Verwijder een betrokkene.
     *
     */
    @DELETE
    @Path("/{uuid}")
    void betrokkenenDestroy(@PathParam("uuid") UUID uuid) throws ApiException, ProcessingException;

    /**
     * Alle betrokkenen opvragen.
     *
     * Alle betrokkenen opvragen.
     *
     */
    @GET
    
    @Produces({ "application/json" })
    PaginatedBetrokkeneList betrokkenenList(@QueryParam("contactnaamAchternaam") String contactnaamAchternaam, @QueryParam("contactnaamVoorletters") String contactnaamVoorletters, @QueryParam("contactnaamVoornaam") String contactnaamVoornaam, @QueryParam("contactnaamVoorvoegselAchternaam") String contactnaamVoorvoegselAchternaam, @QueryParam("hadKlantcontact__nummer") String hadKlantcontactNummer, @QueryParam("hadKlantcontact__url") String hadKlantcontactUrl, @QueryParam("hadKlantcontact__uuid") String hadKlantcontactUuid, @QueryParam("organisatienaam") String organisatienaam, @QueryParam("page") Integer page, @QueryParam("verstrektedigitaalAdres__adres") String verstrektedigitaalAdresAdres, @QueryParam("verstrektedigitaalAdres__url") String verstrektedigitaalAdresUrl, @QueryParam("verstrektedigitaalAdres__uuid") String verstrektedigitaalAdresUuid, @QueryParam("wasPartij__nummer") String wasPartijNummer, @QueryParam("wasPartij__url") String wasPartijUrl, @QueryParam("wasPartij__uuid") String wasPartijUuid) throws ApiException, ProcessingException;

    /**
     * Werk een betrokkene deels bij.
     *
     * Werk een betrokkene deels bij.
     *
     */
    @PATCH
    @Path("/{uuid}")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    Betrokkene betrokkenenPartialUpdate(@PathParam("uuid") UUID uuid, PatchedBetrokkene patchedBetrokkene) throws ApiException, ProcessingException;

    /**
     * Een specifiek betrokkene opvragen.
     *
     * Een specifiek betrokkene opvragen.
     *
     */
    @GET
    @Path("/{uuid}")
    @Produces({ "application/json" })
    Betrokkene betrokkenenRetrieve(@PathParam("uuid") UUID uuid) throws ApiException, ProcessingException;

    /**
     * Werk een betrokkene in zijn geheel bij.
     *
     * Werk een betrokkene in zijn geheel bij.
     *
     */
    @PUT
    @Path("/{uuid}")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    Betrokkene betrokkenenUpdate(@PathParam("uuid") UUID uuid, Betrokkene betrokkene) throws ApiException, ProcessingException;
}
