/**
 * klantinteracties
 *  Description WIP. 
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: standaarden.ondersteuning@vng.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.atos.client.klanten.api;

import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.DELETE;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.PATCH;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.PUT;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.ProcessingException;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.QueryParam;
import net.atos.client.klanten.model.generated.DigitaalAdres;
import net.atos.client.klanten.model.generated.PaginatedDigitaalAdresList;
import net.atos.client.klanten.model.generated.PatchedDigitaalAdres;
import org.eclipse.microprofile.rest.client.annotation.RegisterProvider;
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

import java.util.UUID;

/**
 * klantinteracties
 *
 * <p> Description WIP. 
 *
 */

@RegisterRestClient
@RegisterProvider(ApiExceptionMapper.class)
@Path("/digitaleadressen")
public interface DigitaleAdressenApi  {

    /**
     * Maak een digitaal adres aan.
     *
     * Maak een digitaal adres aan.
     *
     */
    @POST
    
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    DigitaalAdres digitaleadressenCreate(DigitaalAdres digitaalAdres) throws ApiException, ProcessingException;

    /**
     * Verwijder een digitaal adres.
     *
     * Verwijder een digitaal adres.
     *
     */
    @DELETE
    @Path("/{uuid}")
    void digitaleadressenDestroy(@PathParam("uuid") UUID uuid) throws ApiException, ProcessingException;

    /**
     * Alle digitale adressen opvragen.
     *
     * Alle digitale adressen opvragen.
     *
     */
    @GET
    
    @Produces({ "application/json" })
    PaginatedDigitaalAdresList digitaleadressenList(@QueryParam("page") Integer page) throws ApiException, ProcessingException;

    /**
     * Werk een digitaal adres deels bij.
     *
     * Werk een digitaal adres deels bij.
     *
     */
    @PATCH
    @Path("/{uuid}")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    DigitaalAdres digitaleadressenPartialUpdate(@PathParam("uuid") UUID uuid, PatchedDigitaalAdres patchedDigitaalAdres) throws ApiException, ProcessingException;

    /**
     * Een specifiek digitaal adres opvragen.
     *
     * Een specifiek digitaal adres opvragen.
     *
     */
    @GET
    @Path("/{uuid}")
    @Produces({ "application/json" })
    DigitaalAdres digitaleadressenRetrieve(@PathParam("uuid") UUID uuid) throws ApiException, ProcessingException;

    /**
     * Werk een digitaal adres in zijn geheel bij.
     *
     * Werk een digitaal adres in zijn geheel bij.
     *
     */
    @PUT
    @Path("/{uuid}")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    DigitaalAdres digitaleadressenUpdate(@PathParam("uuid") UUID uuid, DigitaalAdres digitaalAdres) throws ApiException, ProcessingException;
}
