/**
 * klantinteracties
 *  Description WIP. 
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: standaarden.ondersteuning@vng.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.atos.client.klanten.api;

import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.DELETE;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.PATCH;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.PUT;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.ProcessingException;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.QueryParam;
import net.atos.client.klanten.model.generated.InterneTaak;
import net.atos.client.klanten.model.generated.PaginatedInterneTaakList;
import net.atos.client.klanten.model.generated.PatchedInterneTaak;
import org.eclipse.microprofile.rest.client.annotation.RegisterProvider;
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * klantinteracties
 *
 * <p> Description WIP. 
 *
 */

@RegisterRestClient
@RegisterProvider(ApiExceptionMapper.class)
@Path("/internetaken")
public interface InterneTakenApi  {

    /**
     * Maak een interne taak aan.
     *
     * Maak een interne taak aan.
     *
     */
    @POST
    
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    InterneTaak internetakenCreate(InterneTaak interneTaak) throws ApiException, ProcessingException;

    /**
     * Verwijder een interne taak.
     *
     * Verwijder een interne taak.
     *
     */
    @DELETE
    @Path("/{uuid}")
    void internetakenDestroy(@PathParam("uuid") UUID uuid) throws ApiException, ProcessingException;

    /**
     * Alle interne taken opvragen.
     *
     * Alle interne taken opvragen.
     *
     */
    @GET
    
    @Produces({ "application/json" })
    PaginatedInterneTaakList internetakenList(@QueryParam("aanleidinggevendKlantcontact__url") String aanleidinggevendKlantcontactUrl, @QueryParam("aanleidinggevendKlantcontact__uuid") UUID aanleidinggevendKlantcontactUuid, @QueryParam("actor__naam") String actorNaam, @QueryParam("klantcontact__nummer") String klantcontactNummer, @QueryParam("klantcontact__uuid") UUID klantcontactUuid, @QueryParam("nummer") String nummer, @QueryParam("page") Integer page, @QueryParam("status") String status, @QueryParam("toegewezenAanActor__url") String toegewezenAanActorUrl, @QueryParam("toegewezenAanActor__uuid") UUID toegewezenAanActorUuid, @QueryParam("toegewezenOp") OffsetDateTime toegewezenOp) throws ApiException, ProcessingException;

    /**
     * Werk een interne taak deels bij.
     *
     * Werk een interne taak deels bij.
     *
     */
    @PATCH
    @Path("/{uuid}")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    InterneTaak internetakenPartialUpdate(@PathParam("uuid") UUID uuid, PatchedInterneTaak patchedInterneTaak) throws ApiException, ProcessingException;

    /**
     * Een specifiek interne taak opvragen.
     *
     * Een specifiek interne taak opvragen.
     *
     */
    @GET
    @Path("/{uuid}")
    @Produces({ "application/json" })
    InterneTaak internetakenRetrieve(@PathParam("uuid") UUID uuid) throws ApiException, ProcessingException;

    /**
     * Werk een interne taak in zijn geheel bij.
     *
     * Werk een interne taak in zijn geheel bij.
     *
     */
    @PUT
    @Path("/{uuid}")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    InterneTaak internetakenUpdate(@PathParam("uuid") UUID uuid, InterneTaak interneTaak) throws ApiException, ProcessingException;
}
