/**
 * klantinteracties
 *  Description WIP. 
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: standaarden.ondersteuning@vng.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.atos.client.klanten.api;

import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.DELETE;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.PATCH;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.PUT;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.ProcessingException;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.QueryParam;
import net.atos.client.klanten.model.generated.ExpandPartij;
import net.atos.client.klanten.model.generated.PaginatedExpandPartijList;
import net.atos.client.klanten.model.generated.Partij;
import net.atos.client.klanten.model.generated.PatchedPartij;
import org.eclipse.microprofile.rest.client.annotation.RegisterProvider;
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

import java.util.List;
import java.util.UUID;

/**
 * klantinteracties
 *
 * <p> Description WIP. 
 *
 */

@RegisterRestClient
@RegisterProvider(ApiExceptionMapper.class)
@Path("/partijen")
public interface PartijenApi  {

    /**
     * Maak een partij aan.
     *
     * Maak een partij aan.
     *
     */
    @POST
    
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    Partij partijenCreate(Partij partij) throws ApiException, ProcessingException;

    /**
     * Verwijder een partij.
     *
     * Verwijder een partij.
     *
     */
    @DELETE
    @Path("/{uuid}")
    void partijenDestroy(@PathParam("uuid") UUID uuid) throws ApiException, ProcessingException;

    /**
     * Alle partijen opvragen.
     *
     * Alle partijen opvragen.
     *
     */
    @GET
    
    @Produces({ "application/json" })
    PaginatedExpandPartijList partijenList(@QueryParam("bezoekadresAdresregel1") String bezoekadresAdresregel1, @QueryParam("bezoekadresAdresregel2") String bezoekadresAdresregel2, @QueryParam("bezoekadresAdresregel3") String bezoekadresAdresregel3, @QueryParam("bezoekadresLand") String bezoekadresLand, @QueryParam("bezoekadresNummeraanduidingId") String bezoekadresNummeraanduidingId, @QueryParam("categorierelatie__categorie__naam") String categorierelatieCategorieNaam, @QueryParam("correspondentieadresAdresregel1") String correspondentieadresAdresregel1, @QueryParam("correspondentieadresAdresregel2") String correspondentieadresAdresregel2, @QueryParam("correspondentieadresAdresregel3") String correspondentieadresAdresregel3, @QueryParam("correspondentieadresLand") String correspondentieadresLand, @QueryParam("correspondentieadresNummeraanduidingId") String correspondentieadresNummeraanduidingId, @QueryParam("expand") List<String> expand, @QueryParam("indicatieActief") Boolean indicatieActief, @QueryParam("indicatieGeheimhouding") Boolean indicatieGeheimhouding, @QueryParam("nummer") String nummer, @QueryParam("page") Integer page, @QueryParam("partijIdentificator__codeObjecttype") String partijIdentificatorCodeObjecttype, @QueryParam("partijIdentificator__codeRegister") String partijIdentificatorCodeRegister, @QueryParam("partijIdentificator__codeSoortObjectId") String partijIdentificatorCodeSoortObjectId, @QueryParam("partijIdentificator__objectId") String partijIdentificatorObjectId, @QueryParam("soortPartij") String soortPartij, @QueryParam("vertegenwoordigdePartij__url") String vertegenwoordigdePartijUrl, @QueryParam("vertegenwoordigdePartij__uuid") UUID vertegenwoordigdePartijUuid) throws ApiException, ProcessingException;

    /**
     * Werk een partij deels bij.
     *
     * Werk een partij deels bij.
     *
     */
    @PATCH
    @Path("/{uuid}")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    Partij partijenPartialUpdate(@PathParam("uuid") UUID uuid, PatchedPartij patchedPartij) throws ApiException, ProcessingException;

    /**
     * Een specifiek partij opvragen.
     *
     * Een specifiek partij opvragen.
     *
     */
    @GET
    @Path("/{uuid}")
    @Produces({ "application/json" })
    ExpandPartij partijenRetrieve(@PathParam("uuid") UUID uuid, @QueryParam("expand") List<String> expand) throws ApiException, ProcessingException;

    /**
     * Werk een partij in zijn geheel bij.
     *
     * Werk een partij in zijn geheel bij.
     *
     */
    @PUT
    @Path("/{uuid}")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    Partij partijenUpdate(@PathParam("uuid") UUID uuid, Partij partij) throws ApiException, ProcessingException;
}
