/**
 * klantinteracties
 *  Description WIP. 
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: standaarden.ondersteuning@vng.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.atos.client.klanten.api;

import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.DELETE;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.PATCH;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.PUT;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.ProcessingException;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.QueryParam;
import net.atos.client.klanten.model.generated.PaginatedRekeningnummerList;
import net.atos.client.klanten.model.generated.PatchedRekeningnummer;
import net.atos.client.klanten.model.generated.Rekeningnummer;
import org.eclipse.microprofile.rest.client.annotation.RegisterProvider;
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

import java.util.UUID;

/**
 * klantinteracties
 *
 * <p> Description WIP. 
 *
 */

@RegisterRestClient
@RegisterProvider(ApiExceptionMapper.class)
@Path("/rekeningnummers")
public interface RekeningnummersApi  {

    /**
     * Maak een rekeningnummer aan.
     *
     * Maak een rekeningnummer aan.
     *
     */
    @POST
    
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    Rekeningnummer rekeningnummersCreate(Rekeningnummer rekeningnummer) throws ApiException, ProcessingException;

    /**
     * Verwijder een rekeningnummer.
     *
     * Verwijder een rekeningnummer.
     *
     */
    @DELETE
    @Path("/{uuid}")
    void rekeningnummersDestroy(@PathParam("uuid") UUID uuid) throws ApiException, ProcessingException;

    /**
     * Alle rekeningnummers opvragen.
     *
     * Alle rekeningnummers opvragen.
     *
     */
    @GET
    
    @Produces({ "application/json" })
    PaginatedRekeningnummerList rekeningnummersList(@QueryParam("bic") String bic, @QueryParam("iban") String iban, @QueryParam("page") Integer page, @QueryParam("uuid") UUID uuid) throws ApiException, ProcessingException;

    /**
     * Werk een rekeningnummer deels bij.
     *
     * Werk een rekeningnummer deels bij.
     *
     */
    @PATCH
    @Path("/{uuid}")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    Rekeningnummer rekeningnummersPartialUpdate(@PathParam("uuid") UUID uuid, PatchedRekeningnummer patchedRekeningnummer) throws ApiException, ProcessingException;

    /**
     * Een specifiek rekeningnummer opvragen.
     *
     * Een specifiek rekeningnummer opvragen.
     *
     */
    @GET
    @Path("/{uuid}")
    @Produces({ "application/json" })
    Rekeningnummer rekeningnummersRetrieve(@PathParam("uuid") UUID uuid) throws ApiException, ProcessingException;

    /**
     * Werk een rekeningnummer in zijn geheel bij.
     *
     * Werk een rekeningnummer in zijn geheel bij.
     *
     */
    @PUT
    @Path("/{uuid}")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    Rekeningnummer rekeningnummersUpdate(@PathParam("uuid") UUID uuid, Rekeningnummer rekeningnummer) throws ApiException, ProcessingException;
}
