/**
 * klantinteracties
 *  Description WIP. 
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: standaarden.ondersteuning@vng.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.atos.client.klanten.api;

import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.DELETE;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.PATCH;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.PUT;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.ProcessingException;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.QueryParam;
import net.atos.client.klanten.model.generated.PaginatedVertegenwoordigdenList;
import net.atos.client.klanten.model.generated.PatchedVertegenwoordigden;
import net.atos.client.klanten.model.generated.Vertegenwoordigden;
import org.eclipse.microprofile.rest.client.annotation.RegisterProvider;
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

import java.util.UUID;

/**
 * klantinteracties
 *
 * <p> Description WIP. 
 *
 */

@RegisterRestClient
@RegisterProvider(ApiExceptionMapper.class)
@Path("/vertegenwoordigingen")
public interface VertegenwoordigingenApi  {

    /**
     * Maak een vertegenwoordiging aan.
     *
     * Maak een vertegenwoordiging aan.
     *
     */
    @POST
    
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    Vertegenwoordigden vertegenwoordigingenCreate(Vertegenwoordigden vertegenwoordigden) throws ApiException, ProcessingException;

    /**
     * Verwijder een vertegenwoordiging.
     *
     * Verwijder een vertegenwoordiging.
     *
     */
    @DELETE
    @Path("/{uuid}")
    void vertegenwoordigingenDestroy(@PathParam("uuid") UUID uuid) throws ApiException, ProcessingException;

    /**
     * Alle vertegenwoordigingen opvragen.
     *
     * Alle vertegenwoordigingen opvragen.
     *
     */
    @GET
    
    @Produces({ "application/json" })
    PaginatedVertegenwoordigdenList vertegenwoordigingenList(@QueryParam("page") Integer page, @QueryParam("vertegenwoordigdePartij__url") String vertegenwoordigdePartijUrl, @QueryParam("vertegenwoordigdePartij__uuid") UUID vertegenwoordigdePartijUuid, @QueryParam("vertegenwoordigendePartij__url") String vertegenwoordigendePartijUrl, @QueryParam("vertegenwoordigendePartij__uuid") UUID vertegenwoordigendePartijUuid) throws ApiException, ProcessingException;

    /**
     * Werk een vertegenwoordiging deels bij.
     *
     * Werk een vertegenwoordiging deels bij.
     *
     */
    @PATCH
    @Path("/{uuid}")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    Vertegenwoordigden vertegenwoordigingenPartialUpdate(@PathParam("uuid") UUID uuid, PatchedVertegenwoordigden patchedVertegenwoordigden) throws ApiException, ProcessingException;

    /**
     * Een specifiek vertegenwoordiging opvragen.
     *
     * Een specifiek vertegenwoordiging opvragen.
     *
     */
    @GET
    @Path("/{uuid}")
    @Produces({ "application/json" })
    Vertegenwoordigden vertegenwoordigingenRetrieve(@PathParam("uuid") UUID uuid) throws ApiException, ProcessingException;

    /**
     * Werk een vertegenwoordiging in zijn geheel bij.
     *
     * Werk een vertegenwoordiging in zijn geheel bij.
     *
     */
    @PUT
    @Path("/{uuid}")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    Vertegenwoordigden vertegenwoordigingenUpdate(@PathParam("uuid") UUID uuid, Vertegenwoordigden vertegenwoordigden) throws ApiException, ProcessingException;
}
