/*
 * SPDX-FileCopyrightText: 2021 Atos
 * SPDX-License-Identifier: EUPL-1.2+
 */

/**
 * @deprecated - use the `GeneratedType`
 * Maps to ScreenObjectTypeEnum.java
 */
export enum ObjectType {
  BESLUIT = "BESLUIT",
  BESLUIT_INFORMATIEOBJECTEN = "BESLUIT_INFORMATIEOBJECTEN",
  ENKELVOUDIG_INFORMATIEOBJECT = "ENKELVOUDIG_INFORMATIEOBJECT",
  SIGNALERINGEN = "SIGNALERINGEN",
  TAAK = "TAAK",
  ZAAK = "ZAAK",
  ZAAK_BESLUITEN = "ZAAK_BESLUITEN",
  ZAAK_ROLLEN = "ZAAK_ROLLEN",
  ZAAK_TAKEN = "ZAAK_TAKEN",
  ZAAK_INFORMATIEOBJECTEN = "ZAAK_INFORMATIEOBJECTEN",
  ZAKEN_VERDELEN = "ZAKEN_VERDELEN",
  ZAKEN_VRIJGEVEN = "ZAKEN_VRIJGEVEN",
  ZAKEN_SIGNALERINGEN = "ZAKEN_SIGNALERINGEN",
  TAKEN_VERDELEN = "TAKEN_VERDELEN",
  TAKEN_VRIJGEVEN = "TAKEN_VRIJGEVEN",
  ANY = "ANY",
}
