version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/main/app/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Amsterdam"
    reviewers:
      - "infonl/dimpact"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Amsterdam"
    reviewers:
      - "infonl/dimpact"
    ignore:
      # Ignore updates for these packages because it is needed for our current WildFly version (26.x)
      - dependency-name: "jakarta.platform:jakarta.jakartaee-api:8.0.0"
      - dependency-name: "org.eclipse.microprofile.rest.client:microprofile-rest-client-api:2.0"
      - dependency-name: "org.eclipse.microprofile.config:microprofile-config-api:2.0"
      - dependency-name: "org.eclipse.microprofile.health:microprofile-health-api:3.1"
      - dependency-name: "org.eclipse.microprofile.fault-tolerance:microprofile-fault-tolerance-api:3.0"
      - dependency-name: "org.jboss.resteasy:resteasy-multipart-provider:4.7.7.Final"
      - dependency-name: "org.wildfly.security:wildfly-elytron-http-oidc:1.19.1.Final"


  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Amsterdam"
    reviewers:
    - "infonl/dimpact"
