#
# SPDX-FileCopyrightText: 2023 Lifely
# SPDX-License-Identifier: EUPL-1.2+
#
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/main/app/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Amsterdam"
    reviewers:
      - "infonl/dimpact"
    groups:
      # group minor and patch Angular updates together
      angular:
        patterns:
          - "@angular/*"
          - "@angular-eslint/*"
        update-types:
          - "minor"
          - "patch"
      # group all updates for ESLint including major, minor, and patch
      eslint:
        patterns:
          - "@typescript-eslint/*"
          - eslint
        update-types:
          - "major"
          - "minor"
          - "patch"
    ignore:
      # ignore major Angular updates since they require manual steps
      - dependency-name: "@angular/*"
        update-types: ["version-update:semver-major"]
      # ignore major Node.js updates. We want to use LTS version
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
      # ignore major Bootstrap updates. Version 5 breaks our BPMN functionality
      - dependency-name: "bootstrap"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/src/e2e/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Amsterdam"
    reviewers:
      - "infonl/dimpact"
    ignore:
      # ignore major Node.js updates. We want to use LTS version
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Amsterdam"
    reviewers:
      - "infonl/dimpact"
    ignore:
      # Ignore updates for these packages because they are provided by the WildFly application server.
      - dependency-name: "jakarta.platform:jakarta.jakartaee-api"
      - dependency-name: "org.eclipse.microprofile.rest.client:microprofile-rest-client-api"
      - dependency-name: "org.eclipse.microprofile.config:microprofile-config-api"
      - dependency-name: "org.eclipse.microprofile.health:microprofile-health-api"
      - dependency-name: "org.eclipse.microprofile.fault-tolerance:microprofile-fault-tolerance-api"
      - dependency-name: "org.jboss.resteasy:resteasy-multipart-provider"
      - dependency-name: "org.wildfly.security:wildfly-elytron-http-oidc"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Amsterdam"
    reviewers:
      - "infonl/dimpact"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Amsterdam"
    reviewers:
      - "infonl/dimpact"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Amsterdam"
    reviewers:
      - "infonl/dimpact"
