services:
  keycloak:
    user: "1000:1000"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  keycloak-database:
    user: "1000:1000"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  zac-database:
    user: "1000:1000"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  openzaak-database:
    user: "1000:1000"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  openzaak.local:
    user: "1000:1000"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:6.2.6
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # This container name must contain a '.' or else Open Zaak will respond with a 400
  # error on certain API requests caused by an internal 'invalid URL' error.
  objecten-api.local:
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  objecten-api-database:
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  objecten-api-import:
    user: "1000:1000"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  objecttypen-api:
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  objecttypen-api-database:
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  objecttypen-api-import:
    user: "1000:1000"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  solr:
    user: "1000:1000"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  opa:
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  openldap:
    user: "1000:1000"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  zgw-referentielijsten-database:
    user: "1000:1000"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  zgw-referentielijsten.local:
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  zgw-referentielijsten-database-init:
    user: "1000:1000"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  gbamock:
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  brpproxy:
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  openklant-database:
    user: "1000:1000"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  openklant:
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  smartdocuments-wiremock:
    user: "1000:1000"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  office-converter:
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  otel-collector:
    user: "1000:1000"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  tempo:
    user: "1000:1000"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  prometheus:
    user: "1000:1000"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    user: "1000:1000"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"

  zac:
    user: "1000:1000"
    # Linux workaround for host.docker.internal support
    # see: https://stackoverflow.com/a/67158212
    extra_hosts:
      - "host.docker.internal:host-gateway"
