package net.atos.zac.configuration

const val ENV_VAR_AUTH_REALM = "AUTH_REALM"
const val ENV_VAR_AUTH_RESOURCE = "AUTH_RESOURCE"
const val ENV_VAR_AUTH_SECRET = "AUTH_SECRET" // TODO: sensitive value
const val ENV_VAR_SUBSYSTEM_OPENTELEMETRY__SAMPLER_TYPE = "SUBSYSTEM_OPENTELEMETRY__SAMPLER_TYPE"
const val ENV_VAR_WILDFLY_OVERRIDING_ENV_VARS = "WILDFLY_OVERRIDING_ENV_VARS"
const val ENV_VAR_ZGW_API_CLIENT_MP_REST_URL = "ZGW_API_CLIENT_MP_REST_URL"

val ZAC_ENVIRONMENT_VARIABLES = listOf(
    ENV_VAR_AUTH_REALM,
    ENV_VAR_AUTH_RESOURCE,
    ENV_VAR_SUBSYSTEM_OPENTELEMETRY__SAMPLER_TYPE,
    ENV_VAR_ZGW_API_CLIENT_MP_REST_URL,
    ENV_VAR_WILDFLY_OVERRIDING_ENV_VARS
)
