{{- if not .Values.nginx.existingConfigmap }}
{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zaakafhandelcomponent.nginx.fullname" . }}
  labels:
  {{- include "zaakafhandelcomponent.nginx.labels" . | nindent 4 }}
data:
  proxy: |
    proxy_pass_header Server;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Scheme $scheme;
    {{- if .Values.nginx.useXForwardedHost }}
    proxy_set_header X-Forwarded-Host $http_host;
    {{ else }}
    proxy_set_header Host $http_host;
    {{- end }}
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    proxy_redirect off;
    proxy_pass_request_headers on;
    proxy_http_version 1.1;  # required if you're using istio, otherwise you get HTTP 426 errors

  default.conf: |
    proxy_cache_path /tmp keys_zone=static_cache:10m;

    map $http_upgrade $connection_upgrade {
      default upgrade;
      '' close;
    }

    server {
      listen       8080 default_server;
      server_name {{ .Values.nginx.allowedHosts  | replace "," " "}} localhost;
      server_tokens off;

      gzip on;
      gzip_http_version 1.0;
      gzip_comp_level 2;
      gzip_min_length 1100;
      gzip_buffers 4 8k;
      gzip_proxied any;
      gzip_types
        # text/html is always compressed by HttpGzipModule
        text/css
        text/javascript
        text/xml
        text/plain
        text/x-component
        application/javascript
        application/json
        application/xml
        application/rss+xml
        font/truetypenginc
        font/opentype
        application/vnd.ms-fontobject
        image/svg+xml;
      gzip_static on;
      gzip_proxied  expired no-cache no-store private auth;
      gzip_disable "MSIE [1-6]\.";
      gzip_vary on;

      add_header Feature-Policy "autoplay 'none'; camera 'none'" always;
      add_header Referrer-Policy "same-origin";
      add_header X-Content-Type-Options "nosniff";
      add_header X-XSS-Protection "1; mode=block";
      add_header Strict-Transport-Security max-age=15768000;

      error_page 555 = @longtimeout;
      error_page 556 = @normal;

      location / {
        include conf.d/proxy;
        set $first "B";
        if ($request_uri ~* '^/websocket') {
          set $first "${first}W";
        }
        if ($first = 'BW') {
          return 555;
        }
        return 556;
      }

      location @normal {
        proxy_connect_timeout 300s;
        proxy_read_timeout 300s;
        client_max_body_size {{ .Values.nginx.client_max_body_size }};
        proxy_pass http://{{ include "zaakafhandelcomponent.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }};
      }

      location @longtimeout {
        client_max_body_size {{ .Values.nginx.client_max_body_size }};
        proxy_read_timeout 1d;
        proxy_send_timeout 1d;
        proxy_pass http://{{ include "zaakafhandelcomponent.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }};
      }

      location ~* \.woff2$ {
        proxy_connect_timeout 300s;
        proxy_read_timeout 300s;
        proxy_cache static_cache;
        proxy_cache_background_update on;
        proxy_cache_lock on;
        proxy_cache_valid 30d;
        expires 30d;
        proxy_set_header Cache-Control private;
        proxy_ignore_headrs Expires Cache-Control;
        proxy_pass http://{{ include "zaakafhandelcomponent.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }};
      }

      location /_health/ {
        access_log off;
        error_log /var/log/nginx/error.log error;
        return 200 'OK';
      }

    }
    {{- if .Values.nginx.api_proxy.enabled }}
    server {
      listen       8081 default_server;
      server_tokens off;

      location {{ .Values.nginx.api_proxy.bag.path }} {
        {{- if not (eq .Values.nginx.api_proxy.bag.key_secret "") }}
        proxy_ssl_certificate_key {{ .Values.nginx.api_proxy.bag.key_secret }};
        {{- end }}
        {{- if not (eq .Values.nginx.api_proxy.bag.client_secret "") }}
        proxy_ssl_certificate {{ .Values.nginx.api_proxy.bag.client_secret }};
        {{- end }}
        {{- if not (eq .Values.nginx.api_proxy.bag.server_secret "") }}
        proxy_ssl_trusted_certificate {{ .Values.nginx.api_proxy.bag.server_secret }};
        {{- end }}
        proxy_pass https://{{ .Values.nginx.api_proxy.bag.host }}{{ .Values.nginx.api_proxy.bag.proxy_path }};
        {{- if .Values.nginx.api_proxy.bag.ssl_verify }}
        proxy_ssl_verify on;
        {{- else }}
        proxy_ssl_verify off;
        {{- end }}
        proxy_ssl_session_reuse on;
        proxy_ssl_server_name on;
        proxy_set_header X-API-KEY "";
        proxy_set_header Host {{ .Values.nginx.api_proxy.bag.host }};
        {{- if not (eq .Values.nginx.api_proxy.bag.apikey_value "") }}
        proxy_set_header {{ .Values.nginx.api_proxy.bag.apikey_header_name }} {{ .Values.nginx.api_proxy.bag.apikey_value }};
        {{- end }}
        proxy_http_version 1.1;
      }
      location {{ .Values.nginx.api_proxy.brp.path }} {
        {{- if not (eq .Values.nginx.api_proxy.brp.key_secret "") }}
        proxy_ssl_certificate_key {{ .Values.nginx.api_proxy.brp.key_secret }};
        {{- end }}
        {{- if not (eq .Values.nginx.api_proxy.brp.client_secret "") }}
        proxy_ssl_certificate {{ .Values.nginx.api_proxy.brp.client_secret }};
        {{- end }}
        {{- if not (eq .Values.nginx.api_proxy.brp.server_secret "") }}
        proxy_ssl_trusted_certificate {{ .Values.nginx.api_proxy.brp.server_secret }};
        {{- end }}
        proxy_pass https://{{ .Values.nginx.api_proxy.brp.host }}{{ .Values.nginx.api_proxy.brp.proxy_path }};
        {{- if .Values.nginx.api_proxy.brp.ssl_verify }}
        proxy_ssl_verify on;
        {{- else }}
        proxy_ssl_verify off;
        {{- end }}
        proxy_ssl_session_reuse on;
        proxy_ssl_server_name on;
        proxy_set_header X-API-KEY "";
        proxy_set_header Host {{ .Values.nginx.api_proxy.brp.host }};
        {{- if not (eq .Values.nginx.api_proxy.brp.x_doelbinding "") }}
        proxy_set_header x-doelbinding "{{ .Values.nginx.api_proxy.brp.x_doelbinding }}";
        {{- end }}
        {{- if not (eq .Values.nginx.api_proxy.brp.apikey_value "") }}
        proxy_set_header {{ .Values.nginx.api_proxy.brp.apikey_header_name }} {{ .Values.nginx.api_proxy.brp.apikey_value }};
        {{- end }}
        proxy_http_version 1.1;
      }
      location {{ .Values.nginx.api_proxy.kvk.zoeken.path }} {
        {{- if not (eq .Values.nginx.api_proxy.kvk.zoeken.key_secret "") }}
        proxy_ssl_certificate_key {{ .Values.nginx.api_proxy.kvk.zoeken.key_secret }};
        {{- end }}
        {{- if not (eq .Values.nginx.api_proxy.kvk.zoeken.client_secret "") }}
        proxy_ssl_certificate {{ .Values.nginx.api_proxy.kvk.zoeken.client_secret }};
        {{- end }}
        {{- if not (eq .Values.nginx.api_proxy.kvk.zoeken.server_secret "") }}
        proxy_ssl_trusted_certificate {{ .Values.nginx.api_proxy.kvk.zoeken.server_secret }};
        {{- end }}
        proxy_pass https://{{ .Values.nginx.api_proxy.kvk.zoeken.host }}{{ .Values.nginx.api_proxy.kvk.zoeken.proxy_path }};
        {{- if .Values.nginx.api_proxy.bag.ssl_verify }}
        proxy_ssl_verify on;
        {{- else }}
        proxy_ssl_verify off;
        {{- end }}
        proxy_ssl_session_reuse on;
        proxy_ssl_server_name on;
        proxy_set_header X-API-KEY "";
        proxy_set_header Host {{ .Values.nginx.api_proxy.kvk.zoeken.host }};
        {{- if not (eq .Values.nginx.api_proxy.kvk.zoeken.apikey_value "") }}
        proxy_set_header {{ .Values.nginx.api_proxy.kvk.zoeken.apikey_header_name }} {{ .Values.nginx.api_proxy.kvk.zoeken.apikey_value }};
        {{- end }}
        proxy_http_version 1.1;
      }
      location {{ .Values.nginx.api_proxy.kvk.basisprofiel.path }} {
        {{- if not (eq .Values.nginx.api_proxy.kvk.basisprofiel.key_secret "") }}
        proxy_ssl_certificate_key {{ .Values.nginx.api_proxy.kvk.basisprofiel.key_secret }};
        {{- end }}
        {{- if not (eq .Values.nginx.api_proxy.kvk.basisprofiel.client_secret "") }}
        proxy_ssl_certificate {{ .Values.nginx.api_proxy.kvk.basisprofiel.client_secret }};
        {{- end }}
        {{- if not (eq .Values.nginx.api_proxy.kvk.basisprofiel.server_secret "") }}
        proxy_ssl_trusted_certificate {{ .Values.nginx.api_proxy.kvk.basisprofiel.server_secret }};
        {{- end }}
        proxy_pass https://{{ .Values.nginx.api_proxy.kvk.basisprofiel.host }}{{ .Values.nginx.api_proxy.kvk.basisprofiel.proxy_path }};
        {{- if .Values.nginx.api_proxy.bag.ssl_verify }}
        proxy_ssl_verify on;
        {{- else }}
        proxy_ssl_verify off;
        {{- end }}
        proxy_ssl_session_reuse on;
        proxy_ssl_server_name on;
        proxy_set_header X-API-KEY "";
        proxy_set_header Host {{ .Values.nginx.api_proxy.kvk.basisprofiel.host }};
        {{- if not (eq .Values.nginx.api_proxy.kvk.basisprofiel.apikey_value "") }}
        proxy_set_header {{ .Values.nginx.api_proxy.kvk.basisprofiel.apikey_header_name }} {{ .Values.nginx.api_proxy.kvk.basisprofiel.apikey_value }};
        {{- end }}
        proxy_http_version 1.1;
      }
      location {{ .Values.nginx.api_proxy.kvk.vestigingsprofiel.path }} {
        {{- if not (eq .Values.nginx.api_proxy.kvk.vestigingsprofiel.key_secret "") }}
        proxy_ssl_certificate_key {{ .Values.nginx.api_proxy.kvk.vestigingsprofiel.key_secret }};
        {{- end }}
        {{- if not (eq .Values.nginx.api_proxy.kvk.vestigingsprofiel.client_secret "") }}
        proxy_ssl_certificate {{ .Values.nginx.api_proxy.kvk.vestigingsprofiel.client_secret }};
        {{- end }}
        {{- if not (eq .Values.nginx.api_proxy.kvk.vestigingsprofiel.server_secret "") }}
        proxy_ssl_trusted_certificate {{ .Values.nginx.api_proxy.kvk.vestigingsprofiel.server_secret }};
        {{- end }}
        proxy_pass https://{{ .Values.nginx.api_proxy.kvk.vestigingsprofiel.host }}{{ .Values.nginx.api_proxy.kvk.vestigingsprofiel.proxy_path }};
        {{- if .Values.nginx.api_proxy.bag.ssl_verify }}
        proxy_ssl_verify on;
        {{- else }}
        proxy_ssl_verify off;
        {{- end }}
        proxy_ssl_session_reuse on;
        proxy_ssl_server_name on;
        proxy_set_header X-API-KEY "";
        proxy_set_header Host {{ .Values.nginx.api_proxy.kvk.vestigingsprofiel.host }};
        {{- if not (eq .Values.nginx.api_proxy.kvk.vestigingsprofiel.apikey_value "") }}
        proxy_set_header {{ .Values.nginx.api_proxy.kvk.vestigingsprofiel.apikey_header_name }} {{ .Values.nginx.api_proxy.kvk.vestigingsprofiel.apikey_value }};
        {{- end }}
        proxy_http_version 1.1;
      }
    }
    {{- end }}
{{- end }}
{{- end }}
