{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zaakafhandelcomponent.nginx.fullname" . }}
  labels:
    {{- include "zaakafhandelcomponent.nginx.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }} : {{ tpl ($value | toString) $ }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
      targetPort: http
  selector:
    {{- include "zaakafhandelcomponent.nginx.selectorLabels" . | nindent 4 }}
{{- end }}
