/**
 * Contactmomenten API
 * Een API om contactmomenten met klanten te registreren of op te vragen.  **Afhankelijkheden**  Deze API is afhankelijk van:  * Autorisaties API * Notificaties API * Klanten API * Zaken API *(optioneel)* * Verzoeken API *(optioneel)* * Documenten API *(optioneel)*  **Autorisatie**  Deze API vereist autorisatie. Je kan de [token-tool](https://zaken-auth.vng.cloud/) gebruiken om JWT-tokens te genereren.  ** Notificaties  Deze API publiceert notificaties op het kanaal `contactmomenten`.  **Main resource**  `contactmoment`    **Kenmerken**  * `bronorganisatie`: Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die de klantinteractie heeft gecreeerd. Dit moet een geldig RSIN zijn van 9 nummers en voldoen aan https://nl.wikipedia.org/wiki/Burgerservicenummer#11-proef * `kanaal`: Het communicatiekanaal waarlangs het CONTACTMOMENT gevoerd wordt  **Resources en acties**   **Handige links**  * [Documentatie](https://zaakgerichtwerken.vng.cloud/standaard) * [Zaakgericht werken](https://zaakgerichtwerken.vng.cloud)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: standaarden.ondersteuning@vng.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.atos.client.contactmomenten.model;

import jakarta.json.bind.annotation.JsonbProperty;


public class Wijzigingen  {

 /**
   * Volledige JSON body van het object zoals dat bestond voordat de actie heeft plaatsgevonden.
  **/
  @JsonbProperty("oud")
  private Object oud;

 /**
   * Volledige JSON body van het object na de actie.
  **/
  @JsonbProperty("nieuw")
  private Object nieuw;

 /**
   * Volledige JSON body van het object zoals dat bestond voordat de actie heeft plaatsgevonden.
   * @return oud
  **/
  public Object getOud() {
    return oud;
  }

  /**
    * Set oud
  **/
  public void setOud(Object oud) {
    this.oud = oud;
  }

  public Wijzigingen oud(Object oud) {
    this.oud = oud;
    return this;
  }

 /**
   * Volledige JSON body van het object na de actie.
   * @return nieuw
  **/
  public Object getNieuw() {
    return nieuw;
  }

  /**
    * Set nieuw
  **/
  public void setNieuw(Object nieuw) {
    this.nieuw = nieuw;
  }

  public Wijzigingen nieuw(Object nieuw) {
    this.nieuw = nieuw;
    return this;
  }


  /**
    * Create a string representation of this pojo.
  **/
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Wijzigingen {\n");

    sb.append("    oud: ").append(toIndentedString(oud)).append("\n");
    sb.append("    nieuw: ").append(toIndentedString(nieuw)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
