/*
 * SPDX-FileCopyrightText: 2026 INFO.nl
 * SPDX-License-Identifier: EUPL-1.2+
 */

package nl.info.zac.util

import jakarta.servlet.Filter
import jakarta.servlet.FilterChain
import jakarta.servlet.ServletRequest
import jakarta.servlet.ServletResponse
import jakarta.servlet.annotation.WebFilter
import jakarta.servlet.http.HttpServletRequest
import jakarta.servlet.http.HttpServletResponse

/**
 * Sets long-lived Cache-Control headers on hashed static assets (.js, .css)
 * so browsers cache them across sessions. index.html is explicitly excluded —
 * it must always be revalidated so the browser picks up new chunk references after a deployment.
 */
@WebFilter(filterName = "staticResourceCacheFilter")
class StaticResourceCacheFilter : Filter {

    override fun doFilter(
        request: ServletRequest,
        response: ServletResponse,
        chain: FilterChain
    ) {
        if (request is HttpServletRequest && response is HttpServletResponse) {
            when {
                // Hashed chunks — safe to cache forever; content hash guarantees freshness
                HASHED_RESOURCE_REGEX.containsMatchIn(request.servletPath) ->
                    response.setHeader("Cache-Control", "public, max-age=31536000, immutable")
                // Assets with ?v= cache-buster (i18n JSON, fonts) — only cache when v= is a valid 8-char hex MD5
                // substring (as generated by cache-busting.js). Guards against stale content bugs from
                // incorrectly versioned asset URLs.
                request.servletPath.startsWith("/assets/") &&
                    MD5_VERSION_REGEX.matches(request.getParameter("v") ?: "") ->
                    response.setHeader("Cache-Control", "public, max-age=31536000, immutable")
                // index.html — always revalidate so new chunk references are picked up
                request.servletPath == "/" || request.servletPath == "/index.html" ->
                    response.setHeader("Cache-Control", "no-cache")
            }
        }
        chain.doFilter(request, response)
    }

    companion object {
        // Angular build output: filename contains an 8-character uppercase content hash before the extension
        private val HASHED_RESOURCE_REGEX = Regex("""-[A-Z0-9]{8}\.(js|css)(\.map)?$""")
        // cache-busting.js generates an 8-character lowercase hex MD5 substring (e.g. 395afa0f)
        private val MD5_VERSION_REGEX = Regex("""^[0-9a-f]{8}$""")
    }
}
