/*
 * SPDX-FileCopyrightText: 2022 Atos
 * SPDX-License-Identifier: EUPL-1.2+
 */

package net.atos.zac.app.zaken.converter;

import java.net.URI;
import java.time.Period;
import java.util.List;

import jakarta.inject.Inject;

import net.atos.client.zgw.ztc.ZTCClientService;
import net.atos.client.zgw.ztc.model.Afleidingswijze;
import net.atos.client.zgw.ztc.model.generated.BrondatumArchiefprocedure;
import net.atos.client.zgw.ztc.model.generated.ResultaatType;
import net.atos.zac.app.zaken.model.RESTResultaattype;
import net.atos.zac.util.PeriodUtil;
import net.atos.zac.util.UriUtil;

public class RESTResultaattypeConverter {

    @Inject
    private ZTCClientService ztcClientService;

    public RESTResultaattype convertResultaattype(final ResultaatType resultaattype) {
        final BrondatumArchiefprocedure.AfleidingswijzeEnum afleidingswijze =
                resultaattype.getBrondatumArchiefprocedure().getAfleidingswijze();
        final RESTResultaattype restResultaattype = new RESTResultaattype();
        restResultaattype.id = UriUtil.uuidFromURI(resultaattype.getUrl());
        restResultaattype.naam = resultaattype.getOmschrijving();
        // compare enum values and not the enums themselves because we have multiple functionally
        // identical enums in our Java client code generated by the OpenAPI Generator
        restResultaattype.vervaldatumBesluitVerplicht =
                Afleidingswijze.VERVALDATUM_BESLUIT.toValue().equals(afleidingswijze.value());
        restResultaattype.besluitVerplicht =
                Afleidingswijze.VERVALDATUM_BESLUIT.toValue().equals(afleidingswijze.value()) ||
                Afleidingswijze.INGANGSDATUM_BESLUIT.toValue().equals(afleidingswijze.value());
        restResultaattype.archiefNominatie = resultaattype.getArchiefnominatie().name();
        restResultaattype.toelichting = resultaattype.getToelichting();
        restResultaattype.naamGeneriek = resultaattype.getOmschrijvingGeneriek();
        restResultaattype.archiefTermijn =
                PeriodUtil.format(Period.parse(resultaattype.getArchiefactietermijn()));
        return restResultaattype;
    }

    public RESTResultaattype convertResultaattypeUri(final URI resultaattypeURI) {
        return convertResultaattype(ztcClientService.readResultaattype(resultaattypeURI));
    }

    public List<RESTResultaattype> convertResultaattypes(final List<ResultaatType> resultaattypes) {
        return resultaattypes.stream()
                .map(this::convertResultaattype)
                .toList();
    }

}
