# Open Notificaties setup configuration
# Note that this file cannot be renamed. It needs to be named 'data.yaml'.

# We do not use OIDC support in our Docker Compose setup
oidc_db_config_enable: False

zgw_consumers_config_enable: True
zgw_consumers:
  services:
    - identifier: autorisaties-api
      label: Autorisaties API
      api_root: http://openzaak.local:8000/autorisaties/api/v1/
      api_type: ac
      auth_type: zgw
      client_id: open-notificaties
      secret: opennotificatiesAutorisatieApiSecret
      user_id: open-notificaties
      user_representation: Open Notificaties
    - identifier: notificaties-api
      label: Notificaties API
      api_root: http://opennotificaties:8000/api/v1/
      api_type: nrc
      auth_type: zgw
      client_id: open-notificaties
      secret: opennotificatiesAutorisatieApiSecret
      user_id: open-notificaties
      user_representation: Open Notificaties Demodam

autorisaties_api_config_enable: True
autorisaties_api:
  # Configure Open Notificaties to make use of Open Zaak's Autorisaties API
  authorizations_api_service_identifier: autorisaties-api

vng_api_common_credentials_config_enable: True
vng_api_common_credentials:
  items:
    # Credentials for Open Zaak to be able to make requests to Open Notificaties
    - identifier: open-zaak
      secret: opennotificatiesOpenzaakSecret
    # Credentials for Open Notificaties, required for autorisaties subscription
    - identifier: open-notificaties
      secret: opennotificatiesAutorisatieApiSecret

notifications_kanalen_config_enable: true
notifications_kanalen_config:
  items:
    - naam: autorisaties
      documentatie_link: http://openzaak.local:8000/ref/kanalen/#/autorisaties
      filters:
        - autorisaties
    - naam: besluittypen
      documentatie_link: http://openzaak.local:8000/ref/kanalen/#/besluittypen
      filters:
        - catalogus
    - naam: informatieobjecttypen
      documentatie_link: http://openzaak.local:8000/ref/kanalen/#/informatieobjecttypen
      filters:
        - catalogus
    - naam: zaaktypen
      documentatie_link: http://openzaak.local:8000/ref/kanalen/#/zaaktypen
      filters:
        - catalogus
    - naam: zaken
      documentatie_link: http://openzaak.local:8000/ref/kanalen/#/zaken
      filters:
        - bronorganisatie
        - zaaktype
        - vertrouwelijkheidaanduiding
    - naam: documenten
      documentatie_link: http://openzaak.local:8000/ref/kanalen/#/documenten
      filters:
        - bronorganisatie
        - informatieobjecttype
        - vertrouwelijkheidaanduiding
    - naam: besluiten
      documentatie_link: http://openzaak.local:8000/ref/kanalen/#/besluiten
      filters:
        - verantwoordelijke_organisatie
        - besluittype

sites_config_enable: true
sites_config:
  items:
    - domain: example.com
      name: Open Notificaties

notifications_config_enable: true
notifications_config:
  notifications_api_service_identifier: notificaties-api
  notification_delivery_max_retries: 1
  notification_delivery_retry_backoff: 2
  notification_delivery_retry_backoff_max: 3

notifications_subscriptions_config_enable: true
notifications_subscriptions_config:
  items:
    - identifier: autorisaties-subscription
      callback_url: http://opennotificaties:8000/api/v1/callbacks
      client_id: open-notificaties
      secret: opennotificatiesAutorisatieApiSecret
      uuid: 0f616bfd-aacc-4d85-a140-2af17a56217b
      channels:
        - autorisaties

notifications_abonnementen_config_enable: true
notifications_abonnementen_config:
  items:
    - uuid: fb4e3474-18c8-474b-94ae-980850ea4a7f
      callback_url: http://host.docker.internal:8080/rest/notificaties
      # TODO: how do we set the client id?
      # client_id: opennotificaties
      auth: openNotificatiesApiSecretKey
      kanalen:
        - naam: zaaktypen
        - naam: zaken
        - naam: documenten
        - naam: besluittypen
        - naam: besluiten


