#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: 2026 INFO.nl
# SPDX-License-Identifier: EUPL-1.2+
#
# Regenerates the pre-migrated Open Zaak database dump that Postgres restores when the
# 'openzaak-database' container starts with an empty data directory. With the dump in place
# Open Zaak finds no database migrations left to apply on start-up.
#
# Run this script after bumping the Open Zaak Docker image version in docker-compose.yaml.
# Set DOCKER_USE_ARM64_CONTAINERS=true to use the arm64 images from docker-compose.arm64-override.yaml.
# Requires Docker Compose 2.24 or newer.
#
# This script must not live in the 'imports/openzaak-database' folder: Postgres executes every
# shell script it finds there when it initializes the database.

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repository_root="$(cd "$script_dir/../.." && pwd)"
dump_file="$script_dir/imports/openzaak-database/00-restore-migrated-database.sql"
project_name="zac-openzaak-dump"

cd "$repository_root"

compose_files=(-f docker-compose.yaml)
if [ -n "${DOCKER_USE_ARM64_CONTAINERS:-}" ]; then
  echo "Using arm64 containers ..."
  compose_files+=(-f docker-compose.arm64-override.yaml)
fi

# Start from a completely empty database: no named volume and no init scripts,
# so that the dump only contains what Open Zaak itself creates on its first start.
empty_initdb_dir="$(mktemp -d)"
override_file="$(mktemp)"
cat > "$override_file" <<EOF
services:
  openzaak-database:
    volumes: !override
      - $empty_initdb_dir:/docker-entrypoint-initdb.d
EOF
compose_files+=(-f "$override_file")

compose() {
  docker compose --env-file /dev/null --project-name "$project_name" "${compose_files[@]}" "$@"
}

cleanup() {
  echo "Removing the temporary Open Zaak containers ..."
  compose down --volumes --remove-orphans --timeout 5 > /dev/null 2>&1 || true
  rm -rf "$empty_initdb_dir" "$override_file"
}
trap cleanup EXIT

# 'config --images' also lists the images of the dependencies of the service, so pick the Open Zaak one
openzaak_image="$(compose config --images openzaak-app.local | grep --max-count 1 'open-zaak')"
echo "Starting $openzaak_image on an empty database and waiting until it is healthy ..."
compose up --detach --wait --wait-timeout 600 openzaak-app.local

echo "Writing $dump_file ..."
{
  echo "-- Open Zaak database schema and initial data as created by $openzaak_image on its first start."
  echo "-- Generated by $(basename "$0") on $(date -u +%Y-%m-%d). Do not edit by hand; rerun that script instead."
  compose exec --no-TTY openzaak-database \
    pg_dump --username openzaak --dbname openzaak --no-owner --no-privileges
} > "$dump_file"

echo "Done. Dump size: $(wc -c < "$dump_file" | tr -d ' ') bytes"
