/*
 * SPDX-FileCopyrightText: 2021 Atos
 * SPDX-License-Identifier: EUPL-1.2+
 */

export enum FieldType {
  INPUT = "INPUT",
  HEADING = "HEADING",
  HIDDEN = "HIDDEN",
  HTML_EDITOR = "HTML_EDITOR",
  PARAGRAPH = "PARAGRAPH",
  TEXTAREA = "TEXTAREA",
  DATE = "DATE",
  DIVIDER = "DIVIDER",
  SELECT = "SELECT",
  MEDEWERKER_GROEP = "MEDEWERKER_GROEP",
  DOCUMENTEN_LIJST = "DOCUMENTEN_LIJST",
  READONLY = "READONLY",
  MESSAGE = "MESSAGE",
}
