@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
TITLE ZAC System Context diagram

Person(citizen, "Citizen", "A citizen within a municipality")
Person(employee, "Employee", "An employee of a municipality")

Enterprise_Boundary(commonGround, "Other Common Ground components") {
    System_Boundary(components, "Common Ground applications") {
        System_Ext(openForms, "Open Formulieren")
        System_Ext(openArchief, "Open Archiefbeheer")
    }

    System_Boundary(utilities, "Common Ground utilities") {
        System_Ext(openNotificaties, "Open Notificaties")
        System_Ext(pabc, "PABC")
        System_Ext(keycloak, "Keycloak")
    }

    System_Boundary(registries, "Common Ground registries") {
        System_Ext(objecten, "Objecten")
        System_Ext(openZaak, "Open Zaak")
        System_Ext(openKlant, "Open Klant")
    }
}

System_Boundary(zacRuntime, "ZAC runtime components") {
    System(zac, "ZAC application\n\n\n")
    System(officeConverter, "OfficeConverter")
    System(opa, "OPA")
    System(solr, "Solr")
}

Enterprise_Boundary(external, "External services") {
    System_Ext(bag, "BAG")
    System_Ext(brp, "BRP")
    System_Ext(kvk, "KVK")
    System_Ext(smtpServer, "SMTP Mail Server")
    System_Ext(smartDocs, "SmartDocuments")
    System_Ext(msOffice, "Microsoft Office Desktop Apps")
}

Rel(citizen, openForms, "Submits case forms")
Rel(employee, zac, "Handles cases")

Rel(openForms, objecten, "Read productaanvraag", "Objecten API")
Rel(openKlant, openNotificaties, "Uses", "ZGW Notificaties API")
Rel(objecten, openNotificaties, "Uses", "ZGW Notificaties API")
Rel(openZaak, openNotificaties, "Uses", "ZGW Notificaties API")

Rel(openArchief, openZaak, "Uses", "ZGW Documenten en Zaken API")

Rel(openNotificaties, zac, "Uses", "ZGW Notificatie API for consumers")

Rel(zac, officeConverter, "Convert to PDF", "OfficeConverter API")
Rel(zac, opa, "Authorisation policies", "OPA API")
Rel(zac, solr, "Search", "Solr API")

Rel(zac, objecten, "Uses", "Objecten API")
Rel(zac, openZaak, "Uses", "ZGW Besluiten, Catalogi, Documenten, en Zaken API")
Rel(zac, openKlant, "Uses", "Klantinteracties API")
Rel(zac, openKlant, "Uses", "Contactgegevens API")
Rel(zac, pabc, "Get employee and group authorisation mappings", "PABC authorisations API")
Rel(zac, keycloak, "Authenticates employees and gets users and groups", "Keycloak API")

Rel(zac, bag, "Get BAG objects", "HaalCentraal BAG Bevragen API")
Rel(zac, brp, "Get personal data", "HaalCentraal BRP Bevragen API")
Rel(zac, kvk, "Get KVK registrations", "KVK Zoeken en Vestigingsprofielen API")
Rel(zac, smtpServer, "Sends mail", "SMTP Mail Server")
Rel(zac, smartDocs, "Creates Office documents", "SmartDocuments API")
Rel(zac, msOffice, "Open and edit documents in Office", "WebDAV API")
Rel(smartDocs, zac, "Uses", "ZAC SmartDocuments Callback API")

Lay_Down(bag, brp)
Lay_Down(brp, kvk)
Lay_Down(kvk, smtpServer)
Lay_Down(smtpServer, smartDocs)
Lay_Down(smartDocs, msOffice)
@enduml
