global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      # listen to the ZAC/WildFly management port exposed on localhost
      - targets: [ 'host.docker.internal:9990' ]
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]
