#
# SPDX-FileCopyrightText: 2022 Atos, 2024 INFO.nl
# SPDX-License-Identifier: EUPL-1.2+
#

apiVersion: v2
name: zaakafhandelcomponent
description: A Helm chart for installing Zaakafhandelcomponent
version: 1.0.83
appVersion: '3.6'
icon: https://raw.githubusercontent.com/infonl/dimpact-zaakafhandelcomponent/49f8dee60948282b546ebdfdc5cff6f8bbef0305/docs/manuals/ZAC-gebruikershandleiding/images/pic.svg
dependencies:
- name: opentelemetry-collector
  repository: '@opentelemetry'
  condition: opentelemetry-collector.enabled
  version: 0.127.2
- name: solr-operator
  repository: '@solr'
  version: 0.9.1
  condition: solr-operator.enabled
maintainers:
- name: Team Dimpact, INFO
  email: teamdimpact@info.nl
  url: https://github.com/infonl/dimpact-zaakafhandelcomponent/discussions
