#
# SPDX-FileCopyrightText: 2022 Atos, 2024 Lifely
# SPDX-License-Identifier: EUPL-1.2+
#

apiVersion: v2
name: zaakafhandelcomponent
description: A Helm chart for installing Zaakafhandelcomponent
version: 0.4.2
appVersion: "latest"
icon: https://raw.githubusercontent.com/infonl/dimpact-zaakafhandelcomponent/49f8dee60948282b546ebdfdc5cff6f8bbef0305/docs/manuals/ZAC-gebruikershandleiding/images/pic.svg
dependencies:
  - name: opentelemetry-collector
    repository: "@opentelemetry"
    condition: opentelemetry-collector.enabled
    version: 0.104.0
  - name: solr
    version: 9.5.1
    repository: "@bitnami"
    condition: solr.enabled
maintainers:
  - name: Team Geneve, INFO
    email: teamdimpact@info.nl
    url: https://www.info.nl
