/**
 * Referentielijsten & Selectielijst API
 *  Een API om referentielijstwaarden en de gemeentelijke selectielijst te benaderen.  ## Selectielijst  De [Gemeentelijke Selectielijst](https://vng.nl/selectielijst) is relevant in het kader van archivering.  **Zaakgericht werken**  Bij het configureren van zaaktypes (en resultaattypes) in de catalogus API refereren een aantal resources naar resources binnen de Selectielijst API. Het gaat dan om de `ProcesType` en `Resultaat` resources.  ## Referentielijsten  Referentielijsten bevat een standaardset aan waarden. Deze waarden zijn net té dynamisch om in een enum opgenomen te worden, maar er is wel behoefte om deze landelijk te standaardiseren. Een voorbeeld hiervan is de set aan mogelijke communicatiekanalen.  ## Autorisatie  Deze APIs zijn alleen-lezen, en behoeven geen autorisatie.  ## Inhoud  De inhoud wordt beheerd door VNG Realisatie. Om de inhoud van referentielijsten bij te werken, contacteer dan VNG Realisatie via e-mail of op Github.  De inhoud van de Gemeentelijke Selectielijst wordt geïmporteerd vanuit de gepubliceerde Excel-bestanden.
 *
 * The version of the OpenAPI document: 1.0.0-alpha
 * Contact: standaarden.ondersteuning@vng.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.atos.client.vrl.model;

import java.net.URI;

import jakarta.json.bind.annotation.JsonbCreator;
import jakarta.json.bind.annotation.JsonbProperty;


public class ProcesType  {

  @JsonbProperty("url")
  private URI url;

 /**
   * Nummer van de selectielijstcategorie
  **/
  @JsonbProperty("nummer")
  private Integer nummer;

 /**
   * Het jaartal waartoe dit ProcesType behoort
  **/
  @JsonbProperty("jaar")
  private Integer jaar;

 /**
   * Benaming van het procestype
  **/
  @JsonbProperty("naam")
  private String naam;

 /**
   * Omschrijving van het procestype
  **/
  @JsonbProperty("omschrijving")
  private String omschrijving;

 /**
   * Toelichting van het procestype
  **/
  @JsonbProperty("toelichting")
  private String toelichting;

 /**
   * Object waar de uitvoering van het proces op van toepassing is en waarvan de bestaans- of geldigheidsduur eventueel van belang is bij het bepalen van de start van de bewaartermijn
  **/
  @JsonbProperty("procesobject")
  private String procesobject;

  public ProcesType() {
  }

 @JsonbCreator
  public ProcesType(
    @JsonbProperty(value = "url", nillable = true) URI url
  ) {
    this.url = url;
  }

 /**
   * Get url
   * @return url
  **/
  public URI getUrl() {
    return url;
  }


 /**
   * Nummer van de selectielijstcategorie
   * minimum: 0
   * maximum: 32767
   * @return nummer
  **/
  public Integer getNummer() {
    return nummer;
  }

  /**
    * Set nummer
  **/
  public void setNummer(Integer nummer) {
    this.nummer = nummer;
  }

  public ProcesType nummer(Integer nummer) {
    this.nummer = nummer;
    return this;
  }

 /**
   * Het jaartal waartoe dit ProcesType behoort
   * minimum: 0
   * maximum: 2147483647
   * @return jaar
  **/
  public Integer getJaar() {
    return jaar;
  }

  /**
    * Set jaar
  **/
  public void setJaar(Integer jaar) {
    this.jaar = jaar;
  }

  public ProcesType jaar(Integer jaar) {
    this.jaar = jaar;
    return this;
  }

 /**
   * Benaming van het procestype
   * @return naam
  **/
  public String getNaam() {
    return naam;
  }

  /**
    * Set naam
  **/
  public void setNaam(String naam) {
    this.naam = naam;
  }

  public ProcesType naam(String naam) {
    this.naam = naam;
    return this;
  }

 /**
   * Omschrijving van het procestype
   * @return omschrijving
  **/
  public String getOmschrijving() {
    return omschrijving;
  }

  /**
    * Set omschrijving
  **/
  public void setOmschrijving(String omschrijving) {
    this.omschrijving = omschrijving;
  }

  public ProcesType omschrijving(String omschrijving) {
    this.omschrijving = omschrijving;
    return this;
  }

 /**
   * Toelichting van het procestype
   * @return toelichting
  **/
  public String getToelichting() {
    return toelichting;
  }

  /**
    * Set toelichting
  **/
  public void setToelichting(String toelichting) {
    this.toelichting = toelichting;
  }

  public ProcesType toelichting(String toelichting) {
    this.toelichting = toelichting;
    return this;
  }

 /**
   * Object waar de uitvoering van het proces op van toepassing is en waarvan de bestaans- of geldigheidsduur eventueel van belang is bij het bepalen van de start van de bewaartermijn
   * @return procesobject
  **/
  public String getProcesobject() {
    return procesobject;
  }

  /**
    * Set procesobject
  **/
  public void setProcesobject(String procesobject) {
    this.procesobject = procesobject;
  }

  public ProcesType procesobject(String procesobject) {
    this.procesobject = procesobject;
    return this;
  }


  /**
    * Create a string representation of this pojo.
  **/
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcesType {\n");

    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    nummer: ").append(toIndentedString(nummer)).append("\n");
    sb.append("    jaar: ").append(toIndentedString(jaar)).append("\n");
    sb.append("    naam: ").append(toIndentedString(naam)).append("\n");
    sb.append("    omschrijving: ").append(toIndentedString(omschrijving)).append("\n");
    sb.append("    toelichting: ").append(toIndentedString(toelichting)).append("\n");
    sb.append("    procesobject: ").append(toIndentedString(procesobject)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
