#
# SPDX-FileCopyrightText: 2022 Atos, 2024 Lifely
# SPDX-License-Identifier: EUPL-1.2+
#

apiVersion: v2
name: zaakafhandelcomponent
description: A Helm chart for installing Zaakafhandelcomponent
version: 0.4.0
appVersion: "latest"
dependencies:
  - name: opentelemetry-collector
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: opentelemetry-collector.enabled
    version: 0.111.2
  - name: solr
    version: 9.5.1
    repository: https://charts.bitnami.com/bitnami
    condition: solr.enabled
maintainers:
  - name: Team Genève, INFO
    email: teamdimpact@info.nl
    url: https://www.info.nl
