apiVersion: v2
name: zaakafhandelcomponent
description: A Helm chart for installing Zaakafhandelcomponent
version: 0.3.1
appVersion: "latest"
dependencies:
  - name: opentelemetry-collector
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: open-telemetry-collector.enabled
    version: 0.55.2
