/**
 * klantinteracties
 * **Warning: Difference between `PUT` and `PATCH`** Both `PUT` and `PATCH` methods can be used to update the fields in a resource, but
 * there is a key difference in how they handle required fields: * The `PUT` method requires you to specify **all mandatory fields** when
 * updating a resource. If any mandatory field is missing, the update will fail. Optional fields are left unchanged if they are not
 * specified. * The `PATCH` method, on the other hand, allows you to update only the fields you specify. Some mandatory fields can be left
 * out, and the resource will only be updated with the provided data, leaving other fields unchanged.
 *
 * The version of the OpenAPI document: 0.1.2 (1)
 * Contact: standaarden.ondersteuning@vng.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.atos.client.klant.model;

import java.util.Objects;

import jakarta.json.bind.annotation.JsonbProperty;


public class ActorIdentificatieGeautomatiseerdeActor {

    @JsonbProperty("actorIdentificatie")
    protected GeautomatiseerdeActor actorIdentificatie;

    /**
     * Get actorIdentificatie
     * 
     * @return actorIdentificatie
     **/
    public GeautomatiseerdeActor getActorIdentificatie() {
        return actorIdentificatie;
    }

    /**
     * Set actorIdentificatie
     */
    public void setActorIdentificatie(GeautomatiseerdeActor actorIdentificatie) {
        this.actorIdentificatie = actorIdentificatie;
    }

    public ActorIdentificatieGeautomatiseerdeActor actorIdentificatie(GeautomatiseerdeActor actorIdentificatie) {
        this.actorIdentificatie = actorIdentificatie;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ActorIdentificatieGeautomatiseerdeActor actorIdentificatieGeautomatiseerdeActor = (ActorIdentificatieGeautomatiseerdeActor) o;
        return Objects.equals(this.actorIdentificatie, actorIdentificatieGeautomatiseerdeActor.actorIdentificatie);
    }

    @Override
    public int hashCode() {
        return Objects.hash(actorIdentificatie);
    }

    /**
     * Create a string representation of this pojo.
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ActorIdentificatieGeautomatiseerdeActor {\n");

        sb.append("    actorIdentificatie: ").append(toIndentedString(actorIdentificatie)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private static String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
