/*
 * SPDX-FileCopyrightText: 2024 INFO.nl
 * SPDX-License-Identifier: EUPL-1.2+
 */

/**
 * klantinteracties
 * **Warning: Difference between `PUT` and `PATCH`** Both `PUT` and `PATCH` methods can be used to update the fields in a resource, but
 * there is a key difference in how they handle required fields: * The `PUT` method requires you to specify **all mandatory fields** when
 * updating a resource. If any mandatory field is missing, the update will fail. Optional fields are left unchanged if they are not
 * specified. * The `PATCH` method, on the other hand, allows you to update only the fields you specify. Some mandatory fields can be left
 * out, and the resource will only be updated with the provided data, leaving other fields unchanged.
 *
 * The version of the OpenAPI document: 0.1.2 (1)
 * Contact: standaarden.ondersteuning@vng.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.atos.client.klant.model;

import java.net.URI;
import java.util.Objects;
import java.util.UUID;

import jakarta.json.bind.annotation.JsonbCreator;
import jakarta.json.bind.annotation.JsonbProperty;


public class ActorKlantcontact {

    /**
     * Unieke (technische) identificatiecode van de actor klantcontact.
     */
    @JsonbProperty("uuid")
    protected UUID uuid;

    /**
     * De unieke URL van deze actor klantcontact binnen deze API.
     */
    @JsonbProperty("url")
    protected URI url;

    /**
     * De gekoppelde 'Actor'.
     */
    @JsonbProperty("actor")
    protected ActorForeignKey actor;

    /**
     * De gekoppelde 'Klantcontact'.
     */
    @JsonbProperty("klantcontact")
    protected KlantcontactForeignKey klantcontact;

    public ActorKlantcontact() {
    }

    @JsonbCreator
    public ActorKlantcontact(
            @JsonbProperty(value = "uuid") UUID uuid,
            @JsonbProperty(value = "url") URI url
    ) {
        this.uuid = uuid;
        this.url = url;
    }

    /**
     * Unieke (technische) identificatiecode van de actor klantcontact.
     * 
     * @return uuid
     **/
    public UUID getUuid() {
        return uuid;
    }


    /**
     * De unieke URL van deze actor klantcontact binnen deze API.
     * 
     * @return url
     **/
    public URI getUrl() {
        return url;
    }


    /**
     * De gekoppelde &#39;Actor&#39;.
     * 
     * @return actor
     **/
    public ActorForeignKey getActor() {
        return actor;
    }

    /**
     * Set actor
     */
    public void setActor(ActorForeignKey actor) {
        this.actor = actor;
    }

    public ActorKlantcontact actor(ActorForeignKey actor) {
        this.actor = actor;
        return this;
    }

    /**
     * De gekoppelde &#39;Klantcontact&#39;.
     * 
     * @return klantcontact
     **/
    public KlantcontactForeignKey getKlantcontact() {
        return klantcontact;
    }

    /**
     * Set klantcontact
     */
    public void setKlantcontact(KlantcontactForeignKey klantcontact) {
        this.klantcontact = klantcontact;
    }

    public ActorKlantcontact klantcontact(KlantcontactForeignKey klantcontact) {
        this.klantcontact = klantcontact;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ActorKlantcontact actorKlantcontact = (ActorKlantcontact) o;
        return Objects.equals(this.uuid, actorKlantcontact.uuid) &&
               Objects.equals(this.url, actorKlantcontact.url) &&
               Objects.equals(this.actor, actorKlantcontact.actor) &&
               Objects.equals(this.klantcontact, actorKlantcontact.klantcontact);
    }

    @Override
    public int hashCode() {
        return Objects.hash(uuid, url, actor, klantcontact);
    }

    /**
     * Create a string representation of this pojo.
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ActorKlantcontact {\n");

        sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
        sb.append("    url: ").append(toIndentedString(url)).append("\n");
        sb.append("    actor: ").append(toIndentedString(actor)).append("\n");
        sb.append("    klantcontact: ").append(toIndentedString(klantcontact)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private static String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
