/*
 * SPDX-FileCopyrightText: 2024 Lifely
 * SPDX-License-Identifier: EUPL-1.2+
 */

/**
 * klantinteracties
 * **Warning: Difference between `PUT` and `PATCH`** Both `PUT` and `PATCH` methods can be used to update the fields in a resource, but
 * there is a key difference in how they handle required fields: * The `PUT` method requires you to specify **all mandatory fields** when
 * updating a resource. If any mandatory field is missing, the update will fail. Optional fields are left unchanged if they are not
 * specified. * The `PATCH` method, on the other hand, allows you to update only the fields you specify. Some mandatory fields can be left
 * out, and the resource will only be updated with the provided data, leaving other fields unchanged.
 *
 * The version of the OpenAPI document: 0.1.2 (1)
 * Contact: standaarden.ondersteuning@vng.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.atos.client.klant.model;

import java.net.URI;
import java.util.Objects;
import java.util.UUID;

import jakarta.json.bind.annotation.JsonbCreator;
import jakarta.json.bind.annotation.JsonbProperty;


public class OnderwerpobjectForeignKey {

    /**
     * Unieke (technische) identificatiecode van het onderwerpdeel.
     */
    @JsonbProperty("uuid")
    protected UUID uuid;

    /**
     * De unieke URL van dit onderwerp object binnen deze API.
     */
    @JsonbProperty("url")
    protected URI url;

    public OnderwerpobjectForeignKey() {
    }

    @JsonbCreator
    public OnderwerpobjectForeignKey(
            @JsonbProperty(value = "url") URI url
    ) {
        this.url = url;
    }

    /**
     * Unieke (technische) identificatiecode van het onderwerpdeel.
     * 
     * @return uuid
     **/
    public UUID getUuid() {
        return uuid;
    }

    /**
     * Set uuid
     */
    public void setUuid(UUID uuid) {
        this.uuid = uuid;
    }

    public OnderwerpobjectForeignKey uuid(UUID uuid) {
        this.uuid = uuid;
        return this;
    }

    /**
     * De unieke URL van dit onderwerp object binnen deze API.
     * 
     * @return url
     **/
    public URI getUrl() {
        return url;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OnderwerpobjectForeignKey onderwerpobjectForeignKey = (OnderwerpobjectForeignKey) o;
        return Objects.equals(this.uuid, onderwerpobjectForeignKey.uuid) &&
               Objects.equals(this.url, onderwerpobjectForeignKey.url);
    }

    @Override
    public int hashCode() {
        return Objects.hash(uuid, url);
    }

    /**
     * Create a string representation of this pojo.
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OnderwerpobjectForeignKey {\n");

        sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
        sb.append("    url: ").append(toIndentedString(url)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private static String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
