/*
 * SPDX-FileCopyrightText: 2025 INFO.nl
 * SPDX-License-Identifier: EUPL-1.2+
 */

/**
 * klantinteracties
 * **Warning: Difference between `PUT` and `PATCH`** Both `PUT` and `PATCH` methods can be used to update the fields in a resource, but
 * there is a key difference in how they handle required fields: * The `PUT` method requires you to specify **all mandatory fields** when
 * updating a resource. If any mandatory field is missing, the update will fail. Optional fields are left unchanged if they are not
 * specified. * The `PATCH` method, on the other hand, allows you to update only the fields you specify. Some mandatory fields can be left
 * out, and the resource will only be updated with the provided data, leaving other fields unchanged.
 *
 * The version of the OpenAPI document: 0.1.2 (1)
 * Contact: standaarden.ondersteuning@vng.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.atos.client.klant.model;

import java.util.Objects;

import jakarta.json.bind.annotation.JsonbProperty;


public class PartijIdentificatorGroepType {

    @JsonbProperty("codeObjecttype")
    protected Objecttype codeObjecttype;

    @JsonbProperty("codeSoortObjectId")
    protected SoortObjectID codeSoortObjectId;

    /**
     * Waarde van de eigenschap die het object identificeert, bijvoorbeeld: '123456788'.
     */
    @JsonbProperty("objectId")
    protected String objectId;

    @JsonbProperty("codeRegister")
    protected Register codeRegister;

    /**
     * Get codeObjecttype
     * 
     * @return codeObjecttype
     **/
    public Objecttype getCodeObjecttype() {
        return codeObjecttype;
    }

    /**
     * Set codeObjecttype
     */
    public void setCodeObjecttype(Objecttype codeObjecttype) {
        this.codeObjecttype = codeObjecttype;
    }

    public PartijIdentificatorGroepType codeObjecttype(Objecttype codeObjecttype) {
        this.codeObjecttype = codeObjecttype;
        return this;
    }

    /**
     * Get codeSoortObjectId
     * 
     * @return codeSoortObjectId
     **/
    public SoortObjectID getCodeSoortObjectId() {
        return codeSoortObjectId;
    }

    /**
     * Set codeSoortObjectId
     */
    public void setCodeSoortObjectId(SoortObjectID codeSoortObjectId) {
        this.codeSoortObjectId = codeSoortObjectId;
    }

    public PartijIdentificatorGroepType codeSoortObjectId(SoortObjectID codeSoortObjectId) {
        this.codeSoortObjectId = codeSoortObjectId;
        return this;
    }

    /**
     * Waarde van de eigenschap die het object identificeert, bijvoorbeeld: &#39;123456788&#39;.
     * 
     * @return objectId
     **/
    public String getObjectId() {
        return objectId;
    }

    /**
     * Set objectId
     */
    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public PartijIdentificatorGroepType objectId(String objectId) {
        this.objectId = objectId;
        return this;
    }

    /**
     * Get codeRegister
     * 
     * @return codeRegister
     **/
    public Register getCodeRegister() {
        return codeRegister;
    }

    /**
     * Set codeRegister
     */
    public void setCodeRegister(Register codeRegister) {
        this.codeRegister = codeRegister;
    }

    public PartijIdentificatorGroepType codeRegister(Register codeRegister) {
        this.codeRegister = codeRegister;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PartijIdentificatorGroepType partijIdentificatorGroepType = (PartijIdentificatorGroepType) o;
        return Objects.equals(this.codeObjecttype, partijIdentificatorGroepType.codeObjecttype) &&
               Objects.equals(this.codeSoortObjectId, partijIdentificatorGroepType.codeSoortObjectId) &&
               Objects.equals(this.objectId, partijIdentificatorGroepType.objectId) &&
               Objects.equals(this.codeRegister, partijIdentificatorGroepType.codeRegister);
    }

    @Override
    public int hashCode() {
        return Objects.hash(codeObjecttype, codeSoortObjectId, objectId, codeRegister);
    }

    /**
     * Create a string representation of this pojo.
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PartijIdentificatorGroepType {\n");

        sb.append("    codeObjecttype: ").append(toIndentedString(codeObjecttype)).append("\n");
        sb.append("    codeSoortObjectId: ").append(toIndentedString(codeSoortObjectId)).append("\n");
        sb.append("    objectId: ").append(toIndentedString(objectId)).append("\n");
        sb.append("    codeRegister: ").append(toIndentedString(codeRegister)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private static String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
