/*
 * SPDX-FileCopyrightText: 2024 Lifely
 * SPDX-License-Identifier: EUPL-1.2+
 */

/**
 * klantinteracties
 * Description WIP.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: standaarden.ondersteuning@vng.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.atos.client.klant.model;

import jakarta.json.bind.annotation.JsonbProperty;

/**
 * Generate a serializer out of a GegevensGroepType. Usage:: >>> class VerlengingSerializer(GegevensGroepSerializer): ... class Meta: ...
 * model = Zaak ... gegevensgroep = 'verlenging' >>> Where ``Zaak.verlenging`` is a :class:``GegevensGroepType``.
 */

public class PartijIdentificatorGroepType {

    /**
     * Type van het object, bijvoorbeeld: 'INGESCHREVEN NATUURLIJK PERSOON'.
     */
    @JsonbProperty("codeObjecttype")
    private String codeObjecttype;

    /**
     * Naam van de eigenschap die het object identificeert, bijvoorbeeld: 'Burgerservicenummer'.
     */
    @JsonbProperty("codeSoortObjectId")
    private String codeSoortObjectId;

    /**
     * Waarde van de eigenschap die het object identificeert, bijvoorbeeld: '123456788'.
     */
    @JsonbProperty("objectId")
    private String objectId;

    /**
     * Binnen het landschap van registers unieke omschrijving van het register waarin het object is geregistreerd, bijvoorbeeld: 'BRP'.
     */
    @JsonbProperty("codeRegister")
    private String codeRegister;

    /**
     * Type van het object, bijvoorbeeld: &#39;INGESCHREVEN NATUURLIJK PERSOON&#39;.
     * 
     * @return codeObjecttype
     **/
    public String getCodeObjecttype() {
        return codeObjecttype;
    }

    /**
     * Set codeObjecttype
     */
    public void setCodeObjecttype(String codeObjecttype) {
        this.codeObjecttype = codeObjecttype;
    }

    public PartijIdentificatorGroepType codeObjecttype(String codeObjecttype) {
        this.codeObjecttype = codeObjecttype;
        return this;
    }

    /**
     * Naam van de eigenschap die het object identificeert, bijvoorbeeld: &#39;Burgerservicenummer&#39;.
     * 
     * @return codeSoortObjectId
     **/
    public String getCodeSoortObjectId() {
        return codeSoortObjectId;
    }

    /**
     * Set codeSoortObjectId
     */
    public void setCodeSoortObjectId(String codeSoortObjectId) {
        this.codeSoortObjectId = codeSoortObjectId;
    }

    public PartijIdentificatorGroepType codeSoortObjectId(String codeSoortObjectId) {
        this.codeSoortObjectId = codeSoortObjectId;
        return this;
    }

    /**
     * Waarde van de eigenschap die het object identificeert, bijvoorbeeld: &#39;123456788&#39;.
     * 
     * @return objectId
     **/
    public String getObjectId() {
        return objectId;
    }

    /**
     * Set objectId
     */
    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public PartijIdentificatorGroepType objectId(String objectId) {
        this.objectId = objectId;
        return this;
    }

    /**
     * Binnen het landschap van registers unieke omschrijving van het register waarin het object is geregistreerd, bijvoorbeeld:
     * &#39;BRP&#39;.
     * 
     * @return codeRegister
     **/
    public String getCodeRegister() {
        return codeRegister;
    }

    /**
     * Set codeRegister
     */
    public void setCodeRegister(String codeRegister) {
        this.codeRegister = codeRegister;
    }

    public PartijIdentificatorGroepType codeRegister(String codeRegister) {
        this.codeRegister = codeRegister;
        return this;
    }


    /**
     * Create a string representation of this pojo.
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PartijIdentificatorGroepType {\n");

        sb.append("    codeObjecttype: ").append(toIndentedString(codeObjecttype)).append("\n");
        sb.append("    codeSoortObjectId: ").append(toIndentedString(codeSoortObjectId)).append("\n");
        sb.append("    objectId: ").append(toIndentedString(objectId)).append("\n");
        sb.append("    codeRegister: ").append(toIndentedString(codeRegister)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private static String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
