/*
 * SPDX-FileCopyrightText: 2025 Lifely
 * SPDX-License-Identifier: EUPL-1.2+
 */

/**
 * klantinteracties
 * **Warning: Difference between `PUT` and `PATCH`** Both `PUT` and `PATCH` methods can be used to update the fields in a resource, but
 * there is a key difference in how they handle required fields: * The `PUT` method requires you to specify **all mandatory fields** when
 * updating a resource. If any mandatory field is missing, the update will fail. Optional fields are left unchanged if they are not
 * specified. * The `PATCH` method, on the other hand, allows you to update only the fields you specify. Some mandatory fields can be left
 * out, and the resource will only be updated with the provided data, leaving other fields unchanged.
 *
 * The version of the OpenAPI document: 0.1.2 (1)
 * Contact: standaarden.ondersteuning@vng.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.atos.client.klant.model;

import java.util.Objects;

import jakarta.json.bind.annotation.JsonbProperty;


public class PartijIdentificatieOrganisatie {

    @JsonbProperty("partijIdentificatie")
    protected Organisatie partijIdentificatie;

    /**
     * Get partijIdentificatie
     * 
     * @return partijIdentificatie
     **/
    public Organisatie getPartijIdentificatie() {
        return partijIdentificatie;
    }

    /**
     * Set partijIdentificatie
     */
    public void setPartijIdentificatie(Organisatie partijIdentificatie) {
        this.partijIdentificatie = partijIdentificatie;
    }

    public PartijIdentificatieOrganisatie partijIdentificatie(Organisatie partijIdentificatie) {
        this.partijIdentificatie = partijIdentificatie;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PartijIdentificatieOrganisatie partijIdentificatieOrganisatie = (PartijIdentificatieOrganisatie) o;
        return Objects.equals(this.partijIdentificatie, partijIdentificatieOrganisatie.partijIdentificatie);
    }

    @Override
    public int hashCode() {
        return Objects.hash(partijIdentificatie);
    }

    /**
     * Create a string representation of this pojo.
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PartijIdentificatieOrganisatie {\n");

        sb.append("    partijIdentificatie: ").append(toIndentedString(partijIdentificatie)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private static String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
