/*
 * SPDX-FileCopyrightText: 2025 Lifely
 * SPDX-License-Identifier: EUPL-1.2+
 */

/**
 * klantinteracties
 * **Warning: Difference between `PUT` and `PATCH`** Both `PUT` and `PATCH` methods can be used to update the fields in a resource, but
 * there is a key difference in how they handle required fields: * The `PUT` method requires you to specify **all mandatory fields** when
 * updating a resource. If any mandatory field is missing, the update will fail. Optional fields are left unchanged if they are not
 * specified. * The `PATCH` method, on the other hand, allows you to update only the fields you specify. Some mandatory fields can be left
 * out, and the resource will only be updated with the provided data, leaving other fields unchanged.
 *
 * The version of the OpenAPI document: 0.1.2 (1)
 * Contact: standaarden.ondersteuning@vng.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.atos.client.klant.model;

import java.net.URI;
import java.util.Objects;
import java.util.UUID;

import jakarta.json.bind.annotation.JsonbCreator;
import jakarta.json.bind.annotation.JsonbProperty;


public class PatchedVertegenwoordigden {

    /**
     * Unieke (technische) identificatiecode van de vertegenwoordigden.
     */
    @JsonbProperty("uuid")
    protected UUID uuid;

    /**
     * De unieke URL van deze vertegenwoordigden binnen deze API.
     */
    @JsonbProperty("url")
    protected URI url;

    /**
     * 'Partij' die een andere 'Partij' vertegenwoordigde.
     */
    @JsonbProperty("vertegenwoordigendePartij")
    protected PartijForeignKey vertegenwoordigendePartij;

    /**
     * 'Partij' vertegenwoordigd wordt door een andere 'Partij'.
     */
    @JsonbProperty("vertegenwoordigdePartij")
    protected PartijForeignKey vertegenwoordigdePartij;

    public PatchedVertegenwoordigden() {
    }

    @JsonbCreator
    public PatchedVertegenwoordigden(
            @JsonbProperty(value = "uuid", nillable = true) UUID uuid,
            @JsonbProperty(value = "url", nillable = true) URI url
    ) {
        this.uuid = uuid;
        this.url = url;
    }

    /**
     * Unieke (technische) identificatiecode van de vertegenwoordigden.
     * 
     * @return uuid
     **/
    public UUID getUuid() {
        return uuid;
    }


    /**
     * De unieke URL van deze vertegenwoordigden binnen deze API.
     * 
     * @return url
     **/
    public URI getUrl() {
        return url;
    }


    /**
     * &#39;Partij&#39; die een andere &#39;Partij&#39; vertegenwoordigde.
     * 
     * @return vertegenwoordigendePartij
     **/
    public PartijForeignKey getVertegenwoordigendePartij() {
        return vertegenwoordigendePartij;
    }

    /**
     * Set vertegenwoordigendePartij
     */
    public void setVertegenwoordigendePartij(PartijForeignKey vertegenwoordigendePartij) {
        this.vertegenwoordigendePartij = vertegenwoordigendePartij;
    }

    public PatchedVertegenwoordigden vertegenwoordigendePartij(PartijForeignKey vertegenwoordigendePartij) {
        this.vertegenwoordigendePartij = vertegenwoordigendePartij;
        return this;
    }

    /**
     * &#39;Partij&#39; vertegenwoordigd wordt door een andere &#39;Partij&#39;.
     * 
     * @return vertegenwoordigdePartij
     **/
    public PartijForeignKey getVertegenwoordigdePartij() {
        return vertegenwoordigdePartij;
    }

    /**
     * Set vertegenwoordigdePartij
     */
    public void setVertegenwoordigdePartij(PartijForeignKey vertegenwoordigdePartij) {
        this.vertegenwoordigdePartij = vertegenwoordigdePartij;
    }

    public PatchedVertegenwoordigden vertegenwoordigdePartij(PartijForeignKey vertegenwoordigdePartij) {
        this.vertegenwoordigdePartij = vertegenwoordigdePartij;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PatchedVertegenwoordigden patchedVertegenwoordigden = (PatchedVertegenwoordigden) o;
        return Objects.equals(this.uuid, patchedVertegenwoordigden.uuid) &&
               Objects.equals(this.url, patchedVertegenwoordigden.url) &&
               Objects.equals(this.vertegenwoordigendePartij, patchedVertegenwoordigden.vertegenwoordigendePartij) &&
               Objects.equals(this.vertegenwoordigdePartij, patchedVertegenwoordigden.vertegenwoordigdePartij);
    }

    @Override
    public int hashCode() {
        return Objects.hash(uuid, url, vertegenwoordigendePartij, vertegenwoordigdePartij);
    }

    /**
     * Create a string representation of this pojo.
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PatchedVertegenwoordigden {\n");

        sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
        sb.append("    url: ").append(toIndentedString(url)).append("\n");
        sb.append("    vertegenwoordigendePartij: ").append(toIndentedString(vertegenwoordigendePartij)).append("\n");
        sb.append("    vertegenwoordigdePartij: ").append(toIndentedString(vertegenwoordigdePartij)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private static String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
