/**
 * klantinteracties
 * **Warning: Difference between `PUT` and `PATCH`** Both `PUT` and `PATCH` methods can be used to update the fields in a resource, but
 * there is a key difference in how they handle required fields: * The `PUT` method requires you to specify **all mandatory fields** when
 * updating a resource. If any mandatory field is missing, the update will fail. Optional fields are left unchanged if they are not
 * specified. * The `PATCH` method, on the other hand, allows you to update only the fields you specify. Some mandatory fields can be left
 * out, and the resource will only be updated with the provided data, leaving other fields unchanged.
 *
 * The version of the OpenAPI document: 0.1.2 (1)
 * Contact: standaarden.ondersteuning@vng.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.atos.client.klant.model;

import java.net.URI;
import java.util.Objects;
import java.util.UUID;

import jakarta.json.bind.annotation.JsonbCreator;
import jakarta.json.bind.annotation.JsonbProperty;


/**
 * Let op: Dit endpoint is EXPERIMENTEEL.
 */

public class PatchedCategorie {

    /**
     * Unieke (technische) identificatiecode van de Categorie.
     */
    @JsonbProperty("uuid")
    protected UUID uuid;

    /**
     * De unieke URL van deze categorie binnen deze API.
     */
    @JsonbProperty("url")
    protected URI url;

    /**
     * Naam van de categorie.
     */
    @JsonbProperty("naam")
    protected String naam;

    public PatchedCategorie() {
    }

    @JsonbCreator
    public PatchedCategorie(
            @JsonbProperty(value = "uuid", nillable = true) UUID uuid,
            @JsonbProperty(value = "url", nillable = true) URI url
    ) {
        this.uuid = uuid;
        this.url = url;
    }

    /**
     * Unieke (technische) identificatiecode van de Categorie.
     * 
     * @return uuid
     **/
    public UUID getUuid() {
        return uuid;
    }


    /**
     * De unieke URL van deze categorie binnen deze API.
     * 
     * @return url
     **/
    public URI getUrl() {
        return url;
    }


    /**
     * Naam van de categorie.
     * 
     * @return naam
     **/
    public String getNaam() {
        return naam;
    }

    /**
     * Set naam
     */
    public void setNaam(String naam) {
        this.naam = naam;
    }

    public PatchedCategorie naam(String naam) {
        this.naam = naam;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PatchedCategorie patchedCategorie = (PatchedCategorie) o;
        return Objects.equals(this.uuid, patchedCategorie.uuid) &&
               Objects.equals(this.url, patchedCategorie.url) &&
               Objects.equals(this.naam, patchedCategorie.naam);
    }

    @Override
    public int hashCode() {
        return Objects.hash(uuid, url, naam);
    }

    /**
     * Create a string representation of this pojo.
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PatchedCategorie {\n");

        sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
        sb.append("    url: ").append(toIndentedString(url)).append("\n");
        sb.append("    naam: ").append(toIndentedString(naam)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private static String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
