/**
 * klantinteracties
 * Description WIP.
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: standaarden.ondersteuning@vng.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.atos.client.klant.model;

import java.net.URI;
import java.util.UUID;

import jakarta.json.bind.annotation.JsonbCreator;
import jakarta.json.bind.annotation.JsonbProperty;


public class PatchedVertegenwoordigden {

    /**
     * Unieke (technische) identificatiecode van de vertegenwoordigden.
     */
    @JsonbProperty("uuid")
    private UUID uuid;

    /**
     * De unieke URL van deze vertegenwoordigden binnen deze API.
     */
    @JsonbProperty("url")
    private URI url;

    /**
     * 'Partij' die een andere 'Partij' vertegenwoordigde.
     */
    @JsonbProperty("vertegenwoordigendePartij")
    private PartijForeignKey vertegenwoordigendePartij;

    /**
     * 'Partij' vertegenwoordigd wordt door een andere 'Partij'.
     */
    @JsonbProperty("vertegenwoordigdePartij")
    private PartijForeignKey vertegenwoordigdePartij;

    public PatchedVertegenwoordigden() {
    }

    @JsonbCreator
    public PatchedVertegenwoordigden(
            @JsonbProperty(value = "uuid", nillable = true) UUID uuid,
            @JsonbProperty(value = "url", nillable = true) URI url
    ) {
        this.uuid = uuid;
        this.url = url;
    }

    /**
     * Unieke (technische) identificatiecode van de vertegenwoordigden.
     * 
     * @return uuid
     **/
    public UUID getUuid() {
        return uuid;
    }


    /**
     * De unieke URL van deze vertegenwoordigden binnen deze API.
     * 
     * @return url
     **/
    public URI getUrl() {
        return url;
    }


    /**
     * &#39;Partij&#39; die een andere &#39;Partij&#39; vertegenwoordigde.
     * 
     * @return vertegenwoordigendePartij
     **/
    public PartijForeignKey getVertegenwoordigendePartij() {
        return vertegenwoordigendePartij;
    }

    /**
     * Set vertegenwoordigendePartij
     */
    public void setVertegenwoordigendePartij(PartijForeignKey vertegenwoordigendePartij) {
        this.vertegenwoordigendePartij = vertegenwoordigendePartij;
    }

    public PatchedVertegenwoordigden vertegenwoordigendePartij(PartijForeignKey vertegenwoordigendePartij) {
        this.vertegenwoordigendePartij = vertegenwoordigendePartij;
        return this;
    }

    /**
     * &#39;Partij&#39; vertegenwoordigd wordt door een andere &#39;Partij&#39;.
     * 
     * @return vertegenwoordigdePartij
     **/
    public PartijForeignKey getVertegenwoordigdePartij() {
        return vertegenwoordigdePartij;
    }

    /**
     * Set vertegenwoordigdePartij
     */
    public void setVertegenwoordigdePartij(PartijForeignKey vertegenwoordigdePartij) {
        this.vertegenwoordigdePartij = vertegenwoordigdePartij;
    }

    public PatchedVertegenwoordigden vertegenwoordigdePartij(PartijForeignKey vertegenwoordigdePartij) {
        this.vertegenwoordigdePartij = vertegenwoordigdePartij;
        return this;
    }


    /**
     * Create a string representation of this pojo.
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PatchedVertegenwoordigden {\n");

        sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
        sb.append("    url: ").append(toIndentedString(url)).append("\n");
        sb.append("    vertegenwoordigendePartij: ").append(toIndentedString(vertegenwoordigendePartij)).append("\n");
        sb.append("    vertegenwoordigdePartij: ").append(toIndentedString(vertegenwoordigdePartij)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private static String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
