/*
 * SPDX-FileCopyrightText: 2022 Atos, 2024 Lifely
 * SPDX-License-Identifier: EUPL-1.2+
 */
package net.atos.zac.app.zaken.converter

import jakarta.inject.Inject
import net.atos.client.zgw.ztc.ZTCClientService
import net.atos.client.zgw.ztc.model.Afleidingswijze
import net.atos.client.zgw.ztc.model.generated.ResultaatType
import net.atos.zac.app.zaken.model.RESTResultaattype
import net.atos.zac.util.PeriodUtil
import net.atos.zac.util.UriUtil
import java.net.URI
import java.time.Period

class RESTResultaattypeConverter @Inject constructor(
    private val ztcClientService: ZTCClientService
) {
    fun convertResultaattype(resultaattype: ResultaatType) =
        RESTResultaattype(
            id = UriUtil.uuidFromURI(resultaattype.url),
            naam = resultaattype.omschrijving,
            toelichting = resultaattype.toelichting,
            archiefNominatie = resultaattype.archiefnominatie.name,
            archiefTermijn = resultaattype.archiefactietermijn?.let {
                PeriodUtil.format(Period.parse(it))
            },
            besluitVerplicht = resultaattype.brondatumArchiefprocedure?.afleidingswijze?.let {
                Afleidingswijze.VERVALDATUM_BESLUIT.toValue() == it.value() ||
                    Afleidingswijze.INGANGSDATUM_BESLUIT.toValue() == it.value()
            } ?: false,
            naamGeneriek = resultaattype.omschrijvingGeneriek,
            // compare enum values and not the enums themselves because we have multiple functionally
            // identical enums in our Java client code generated by the OpenAPI Generator
            vervaldatumBesluitVerplicht = resultaattype.brondatumArchiefprocedure?.afleidingswijze?.let {
                Afleidingswijze.VERVALDATUM_BESLUIT.toValue() == it.value()
            } ?: false
        )

    fun convertResultaattypeUri(resultaattypeURI: URI) =
        convertResultaattype(ztcClientService.readResultaattype(resultaattypeURI))

    fun convertResultaattypes(resultaattypes: List<ResultaatType>): List<RESTResultaattype> =
        resultaattypes.stream()
            .map { this.convertResultaattype(it) }
            .toList()
}
