/**
 * klantinteracties
 *  Description WIP. 
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: standaarden.ondersteuning@vng.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.atos.client.klanten.model;

import jakarta.json.bind.annotation.JsonbCreator;
import jakarta.json.bind.annotation.JsonbProperty;

import java.net.URI;
import java.util.UUID;

/**
  * Set gegevensgroepdata from validated nested data.  Usage: include the mixin on the ModelSerializer that has gegevensgroepen.
  */

public class PatchedOnderwerpobject  {
  
 /**
  * Unieke (technische) identificatiecode van het onderwerpdeel.
  */
  @JsonbProperty("uuid")
  private UUID uuid;

 /**
  * De unieke URL van dit klantcontact binnen deze API.
  */
  @JsonbProperty("url")
  private URI url;

 /**
  * 'Klantcontact' ging over 'Onderwerpobject'
  */
  @JsonbProperty("klantcontact")
  private KlantcontactForeignKey klantcontact;

 /**
  * 'Onderwerpobject' was 'Klantcontact'
  */
  @JsonbProperty("wasKlantcontact")
  private KlantcontactForeignKey wasKlantcontact;

 /**
  * Gegevens die een onderwerpobject in een extern register uniek identificeren.
  */
  @JsonbProperty("onderwerpobjectidentificator")
  private Onderwerpobjectidentificator onderwerpobjectidentificator;

  public PatchedOnderwerpobject() {
  }

 @JsonbCreator
  public PatchedOnderwerpobject(
    @JsonbProperty(value = "uuid", nillable = true) UUID uuid, 
    @JsonbProperty(value = "url", nillable = true) URI url
  ) {
    this.uuid = uuid;
    this.url = url;
  }
  
  /**
   * Unieke (technische) identificatiecode van het onderwerpdeel.
   * @return uuid
   **/
  public UUID getUuid() {
    return uuid;
  }


  /**
   * De unieke URL van dit klantcontact binnen deze API.
   * @return url
   **/
  public URI getUrl() {
    return url;
  }


  /**
   * &#39;Klantcontact&#39; ging over &#39;Onderwerpobject&#39;
   * @return klantcontact
   **/
  public KlantcontactForeignKey getKlantcontact() {
    return klantcontact;
  }

  /**
   * Set klantcontact
   */
  public void setKlantcontact(KlantcontactForeignKey klantcontact) {
    this.klantcontact = klantcontact;
  }

  public PatchedOnderwerpobject klantcontact(KlantcontactForeignKey klantcontact) {
    this.klantcontact = klantcontact;
    return this;
  }

  /**
   * &#39;Onderwerpobject&#39; was &#39;Klantcontact&#39;
   * @return wasKlantcontact
   **/
  public KlantcontactForeignKey getWasKlantcontact() {
    return wasKlantcontact;
  }

  /**
   * Set wasKlantcontact
   */
  public void setWasKlantcontact(KlantcontactForeignKey wasKlantcontact) {
    this.wasKlantcontact = wasKlantcontact;
  }

  public PatchedOnderwerpobject wasKlantcontact(KlantcontactForeignKey wasKlantcontact) {
    this.wasKlantcontact = wasKlantcontact;
    return this;
  }

  /**
   * Gegevens die een onderwerpobject in een extern register uniek identificeren.
   * @return onderwerpobjectidentificator
   **/
  public Onderwerpobjectidentificator getOnderwerpobjectidentificator() {
    return onderwerpobjectidentificator;
  }

  /**
   * Set onderwerpobjectidentificator
   */
  public void setOnderwerpobjectidentificator(Onderwerpobjectidentificator onderwerpobjectidentificator) {
    this.onderwerpobjectidentificator = onderwerpobjectidentificator;
  }

  public PatchedOnderwerpobject onderwerpobjectidentificator(Onderwerpobjectidentificator onderwerpobjectidentificator) {
    this.onderwerpobjectidentificator = onderwerpobjectidentificator;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PatchedOnderwerpobject {\n");
    
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    klantcontact: ").append(toIndentedString(klantcontact)).append("\n");
    sb.append("    wasKlantcontact: ").append(toIndentedString(wasKlantcontact)).append("\n");
    sb.append("    onderwerpobjectidentificator: ").append(toIndentedString(onderwerpobjectidentificator)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
