name: E2E Tests

on:
  workflow_dispatch:

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    environment: e2e

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Start containers
        run: docker compose --profile zac up -d

      - name: Docker ps
        run: docker ps

      - name: Netstat
        run: netstat -lt

      - name: Install deps
        run: cd src/main/app && npm run e2e:install

      - name: Install Playwright Browsers
        run: cd src/main/app/e2e && npx playwright install --with-deps

      - name: Run test
        run: cd src/main/app && npm run e2e:run

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose-e2e.yml" down
