  name: E2E Tests

  on:
    workflow_dispatch:

  jobs:
    docker:
      timeout-minutes: 10
      runs-on: ubuntu-latest
      environment: e2e

      steps:
        - name: Checkout
          uses: actions/checkout@v1

        - name: Start containers
          run: docker compose --profile zac up -d

        - name: Run tests
          run: cd src/main/app && npm run e2e:start

        - name: Stop containers
          if: always()
          run: docker-compose -f "docker-compose-e2e.yml" down
