name: Check SPDX Copyright Headers

on:
  pull_request

jobs:
  check-spdx-headers:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: enarx/spdx@master
        with:
          licenses: EUPL-1.2+
