#
# SPDX-FileCopyrightText: 2023 INFO.nl
# SPDX-License-Identifier: EUPL-1.2+
#
name: Check for conventional commits

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  contents: read
  checks: write

jobs:
  check-for-conventional-commits:
    runs-on: ubuntu-24.04
    steps:
      - name: check-for-cc
        id: check-for-cc
        uses: agenthunt/conventional-commit-checker-action@9e552d650d0e205553ec7792d447929fc78e012b # v2.0.0
