#
# SPDX-FileCopyrightText: 2023 INFO.nl
# SPDX-License-Identifier: EUPL-1.2+
#
name: Cleanup cache after PR close

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write
  actions: write

jobs:
  cleanup-branch-cache:
    runs-on: ubuntu-26.04
    steps:
      - uses: Friedinger/DeleteBranchCaches@5a7cc6a4d76f1200cb44dcfdffbd28e82ab2a51f # v3.0.0
        with:
          github-token: ${{ github.token }}
          # Specify explicitly because the ref at the time of merging will be a branch name such as 'main', 'develop'
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
