#
# SPDX-FileCopyrightText: 2023 Lifely
# SPDX-License-Identifier: EUPL-1.2+
#
name: Trivy code scanner

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    # ignore CodeQL analysis when only Markdown files have changed
    paths-ignore:
      - '**/*.md'
  schedule:
    - cron: "21 11 * * 0"

permissions:
  # Required for uploading SARIF reports
  security-events: write

jobs:
  build:
    name: Run Trivy code scanner
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
