#
# SPDX-FileCopyrightText: 2024 INFO.nl
# SPDX-License-Identifier: EUPL-1.2+
#
name: Trivy Docker image scan

on:
  schedule:
    - cron: "0 3 * * 1-5"
  workflow_dispatch:

env:
  ZAC_IMAGE_URL: 'ghcr.io/infonl/zaakafhandelcomponent:latest'

permissions:
  security-events: write
  contents: read

jobs:
  trivy:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Pull Docker Image
        run: docker pull ${{ env.ZAC_IMAGE_URL }}

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # 0.35.0
        with:
          image-ref: ${{ env.ZAC_IMAGE_URL }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          # limit the severities even when using Sarif
          # or else all vulnerabilities will be reported
          limit-severities-for-sarif: true
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy Scan Results to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@c10b8064de6f491fea524254123dbe5e09572f13 # v4.35.1
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'trivy-docker-image'
