#
# SPDX-FileCopyrightText: 2025 INFO.nl
# SPDX-License-Identifier: EUPL-1.2+
#
name: Update OWASP Dependency Check Database

on:
  schedule:
    # Run weekly on Monday at 1:00 AM UTC
    - cron: "0 1 * * 1"
  workflow_dispatch:

permissions:
  contents: read

env:
  JAVA_VERSION: "21.0.8"

jobs:
  update-db:
    name: Update OWASP Database
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup JDK
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4.4.2

      - name: Restore OWASP Dependency Check database
        uses: actions/cache/restore@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        id: restore-cache
        with:
          path: ~/.gradle/dependency-check-data
          key: owasp-dependency-check-db
          restore-keys: |
            owasp-dependency-check-

      - name: Update OWASP Dependency Check database
        run: |
          echo "🔄 Updating OWASP Dependency Check database..."
          ./gradlew dependencyCheckUpdate --no-configuration-cache
          
          # Show database info
          echo "📊 OWASP database cache status:"
          du -sh ~/.gradle/dependency-check-data
          ls -la ~/.gradle/dependency-check-data/*/odc.mv.db 2>/dev/null | head -3 || true

      - name: Save updated OWASP database
        uses: actions/cache/save@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: ~/.gradle/dependency-check-data
          key: owasp-dependency-check-db
