#
# SPDX-FileCopyrightText: 2024 Lifely
# SPDX-License-Identifier: EUPL-1.2+
#
name: Update Docker images in our Docker Compose file

# This workflow uses the Update Gradle Wrapper action to create a Pull Request if there is a new Gradle Wrapper version available.
# Do note that this PR does _not_ automatically trigger any other workflows.
# As a workaround to trigger our normal PR workflows you can manually close and then immediately reopen the PR. See:
# https://github.com/gradle-update/update-gradle-wrapper-action#running-ci-workflows-in-pull-requests-created-by-the-action

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read
  pull-requests: read

jobs:
  flow:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
      packages: read
    steps:
      - uses: actions/checkout@v4

      - name: simple-compose-service-updates
        uses: sbe-arg/simple-compose-service-updates@v1.1.0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
