name: Generates and updates a publiccode.yaml file

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Update publiccode.yaml
        uses: OpenCatalogi/publiccode-action@0d7f76c2154b2db87ca8a1df087dbf17eecfe10e # 1.3.5