name: Generate a publiccode.yaml file

permissions:
  contents: write

on:
  # TEST only
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Update publiccode.yaml
        uses: OpenCatalogi/publiccode-action@0d7f76c2154b2db87ca8a1df087dbf17eecfe10e # 1.3.5
