/*
 * SPDX-FileCopyrightText: 2026 INFO.nl
 * SPDX-License-Identifier: EUPL-1.2+
 */
package nl.info.zac.documentcreation

import jakarta.enterprise.inject.Instance
import jakarta.inject.Inject
import jakarta.inject.Singleton
import nl.info.zac.authentication.LoggedInUser
import nl.info.zac.util.AllOpen
import nl.info.zac.util.NoArgConstructor
import org.apache.commons.collections4.map.LRUMap
import java.util.Collections
import java.util.UUID

/**
 * Remembers the user that started a document creation, so the unauthenticated SmartDocuments callback can
 * act as that user. The token is generated by ZAC, so a caller cannot name a user itself.
 */
@Singleton
@NoArgConstructor
@AllOpen
class DocumentCreationUserStore @Inject constructor(
    private val loggedInUserInstance: Instance<LoggedInUser>
) {
    companion object {
        const val TOKEN_MAP_MAX_SIZE = 1000
    }

    private val tokenMap: MutableMap<String, LoggedInUser> =
        Collections.synchronizedMap(LRUMap(TOKEN_MAP_MAX_SIZE))

    fun createToken(): String =
        UUID.randomUUID().toString().also { tokenMap[it] = loggedInUserInstance.get() }

    /** Consumes the token, so a callback URL cannot be replayed to create more documents as its user. */
    fun consumeUser(token: String): LoggedInUser? = tokenMap.remove(token)
}
