/*
 * SPDX-FileCopyrightText: 2026 INFO.nl
 * SPDX-License-Identifier: EUPL-1.2+
 */
package nl.info.zac.documentcreation

import jakarta.enterprise.inject.Instance
import jakarta.inject.Inject
import jakarta.inject.Singleton
import nl.info.zac.authentication.LoggedInUser
import nl.info.zac.util.AllOpen
import nl.info.zac.util.NoArgConstructor
import org.apache.commons.collections4.map.LRUMap
import java.time.Duration
import java.time.Instant
import java.util.Collections
import java.util.UUID

/**
 * Remembers the user that started a document creation, so the unauthenticated SmartDocuments callback can
 * act as that user. The token is generated by ZAC, so a caller cannot name a user itself.
 */
@Singleton
@NoArgConstructor
@AllOpen
class DocumentCreationUserStore @Inject constructor(
    private val loggedInUserInstance: Instance<LoggedInUser>
) {
    companion object {
        const val TOKEN_MAP_MAX_SIZE = 1000

        /** Long enough to finish a SmartDocuments wizard, short enough that an abandoned URL stops working. */
        val TOKEN_VALIDITY: Duration = Duration.ofMinutes(60)
    }

    private data class TokenData(val loggedInUser: LoggedInUser, val expiresAt: Instant)

    private val tokenMap: MutableMap<String, TokenData> =
        Collections.synchronizedMap(LRUMap(TOKEN_MAP_MAX_SIZE))

    fun createToken(now: Instant = Instant.now()): String =
        UUID.randomUUID().toString().also {
            tokenMap[it] = TokenData(loggedInUserInstance.get(), now.plus(TOKEN_VALIDITY))
        }

    /** Consumes the token, so a callback URL cannot be replayed to create more documents as its user. */
    fun consumeUser(token: String, now: Instant = Instant.now()): LoggedInUser? =
        tokenMap.remove(token)?.takeIf { now.isBefore(it.expiresAt) }?.loggedInUser
}
