apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zaakafhandelcomponent.fullname" . }}
  labels:
    {{- include "zaakafhandelcomponent.labels" . | nindent 4 }}
stringData:
  AUTH_SECRET: "{{ required "Valid .Values.auth.secret entry required!" .Values.auth.secret | toString }}"
  BAG_API_KEY: "{{ required "Valid .Values.bagApi.apiKey entry required!" .Values.bagApi.apiKey | toString }}"
  BRP_API_KEY: "{{ required "Valid .Values.brpApi.apiKey entry required!" .Values.brpApi.apiKey | toString }}"
  DB_PASSWORD: "{{ required "Valid .Values.db.password entry required!" .Values.db.password | toString }}"
  KEYCLOAK_ADMIN_CLIENT_SECRET: "{{ required "Valid .Values.keycloak.adminClient.secret entry required!" .Values.keycloak.adminClient.secret | toString }}"
  KLANTINTERACTIES_API_TOKEN: "{{ required "Valid .Values.klantinteractiesApi.token entry required!" .Values.klantinteractiesApi.token | toString }}"
  KVK_API_KEY: "{{ required "Valid .Values.kvkApi.apiKey entry required!" .Values.kvkApi.apiKey | toString }}"
  OBJECTS_API_TOKEN: "{{ required "Valid .Values.objectenApi.token entry required!" .Values.objectenApi.token | toString }}"
  OBJECTTYPES_API_TOKEN: "{{ required "Valid .Values.objecttypenApi.token entry required!" .Values.objecttypenApi.token | toString }}"
  OPEN_NOTIFICATIONS_API_SECRET_KEY: "{{ required "Valid .Values.notificationsSecretKey entry required!" .Values.notificationsSecretKey | toString }}"
  {{- if .Values.smartDocuments.enabled }}
  SMARTDOCUMENTS_AUTHENTICATION: "{{ required "Valid .Values.smartDocuments.authentication entry required!" .Values.smartDocuments.authentication | toString }}"
  {{- end }}
  SMTP_PASSWORD: "{{ .Values.mail.smtp.password | default "smtpPassword" | toString }}"
  SMTP_USERNAME: "{{ .Values.mail.smtp.username | default "smtpUsername" | toString }}"
  ZGW_API_SECRET: "{{ required "Valid .Values.zgwApis.secret entry required!" .Values.zgwApis.secret | toString }}"
