apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "zaakafhandelcomponent.fullname" . }}-signaleren
  labels:
    {{- include "zaakafhandelcomponent.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.signaleringen.sendZaakSignaleringenSchedule | quote }}
  concurrencyPolicy: {{ .Values.signaleringen.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.signaleringen.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.signaleringen.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "zaakafhandelcomponent.labels" . | nindent 12 }}
        spec:
          {{- with .Values.signaleringen.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "zaakafhandelcomponent.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.signaleringen.securityContext | nindent 12 }}
          restartPolicy: {{ .Values.signaleringen.restartPolicy }}
          containers:
            - name: {{ include "zaakafhandelcomponent.fullname" . }}-signaleren
              image: "{{ .Values.global.curlImage.repository }}:{{ .Values.global.curlImage.tag }}"
              imagePullPolicy: {{ .Values.global.curlImage.pullPolicy }}
              resources: 
                {{- toYaml .Values.signaleringen.resources | nindent 16 }}
              args:
                - -H
                - 'X-API-KEY: {{ .Values.zacInternalEndpointsApiKey }}'
                - {{ printf "http://%s.%s/rest/internal/signaleringen/send-signaleringen" (include "zaakafhandelcomponent.fullname" .) .Release.Namespace }}
          {{- with .Values.signaleringen.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.signaleringen.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.signaleringen.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
